### ISSUE TITLE
Additional functions for admin/includes/functions/general.php

### ISSUE THREAD

**Issue by zipurman** [gburton/CE-Phoenix#1001]
I added a couple of function and have tested. 

Similar to: function tep_cfg_select_option

I have created: tep_cfg_color_picker( $key_value, $key = '')  which uses http://itsjavi.com/bootstrap-colorpicker from a required /hook/admin/siteWide/bootStrapColorPicker.php which just loads the css/js from CDN.

I have also created tep_cfg_select_pull_down($select_options, $key_value, $key = '') which is similar to tep_cfg_select_option but it offers a HTML SELECT drop down with the array of values, This is useful for longer lists and could (if wanted) be added as a catch on tep_cfg_select_option if the count($select_options) was too big, it could pass the control over to the select list instead. Or it could just be added when needed.

Both tested and pushed to my fork. I can request a pull if you want or I can adjust.

Let me know your thoughts when you have time.

**Comment by zipurman** [comment]
By the way, in the config ... this works for modules: (tested)

`public function get_parameters() {

            return [
                'MODULE_HEADER_TAGS_ZIPUR_HEADER_MESSAGE_STATUS' => [
                    'title' => 'Enable Information Links Footer Module',
                    'value' => 'True',
                    'desc' => 'Do you want to allow Zipur Header Messages to be added to the page header?',
                    'set_func' => "tep_cfg_select_pull_down(['True', 'False', 'Maybe', 'No', 'Testing'], ",
                ],
                'MODULE_HEADER_TAGS_ZIPUR_HEADER_MESSAGE_TEXT' => [
                    'title' => 'Your Message',
                    'value' => '',
                    'desc' => 'Your visitors will see this message.',
                ],
                'MODULE_HEADER_TAGS_ZIPUR_HEADER_MESSAGE_BACKGROUND_COLOR' => [
                    'title' => 'Background Color',
                    'value' => '#c28b8b',
                    'desc' => 'Background Color.',
                    'set_func' => "tep_cfg_color_picker( ",
                ],
                'MODULE_HEADER_TAGS_ZIPUR_HEADER_MESSAGE_TEXT_COLOR' => [
                    'title' => 'Text Color',
                    'value' => '#000000',
                    'desc' => 'Text Color.',
                    'set_func' => "tep_cfg_color_picker( ",

                ],
                'MODULE_HEADER_TAGS_ZIPUR_HEADER_MESSAGE_COOKIE_ID' => [
                    'title' => 'Cookie ID',
                    'value' => '1',
                    'desc' => 'Change this id to make all users see the message right away. Even people who confirmed last message within the last 24 hours.',
                ],
            ];

        }`

**Comment by zipurman** [comment]
<img width="539" alt="Screen Shot 2020-08-20 at 7 01 09 PM" src="https://user-images.githubusercontent.com/32114250/90840563-8c8c9d80-e317-11ea-8b63-7cb1c7524cb4.png">

**Comment by ecartz** [comment]
For the immediate term, consider making it a static method on your class and calling it 

```
                'set_func' => "zipur_message_header::pick_color( ",
```

It doesn't actually need to be a function from admin/includes/functions/general.php

Example:  https://github.com/gburton/CE-Phoenix/blob/master/includes/modules/payment/pm2checkout.php#L168

**Comment by zipurman** [comment]
Thanks ecartz. I dont actually need this in any of my add-ons, but if the core had it I'd use it. I am just testing out how to submit ideas and get more involved in helping with adding core functionality. I realize that is a small group ... but I am interested in helping with whatever core coding needs to be done.

**Comment by gburton** [comment]
> I dont actually need this in any of my add-ons, but if the core had it I'd use it.

People could say the same about anything...ranging from a simple language change to a discount system or a theme or anything.  Just because someone would use it, doesn't make it a core need.

If 95% of shopowners would use something, then we'd consider a core addition.  Or if something is already in core and could be done in a better, more effective and modern way, then we would either remove from core (to allow an addon to do it better) or to update core appropriately.
