### ISSUE TITLE
Bootstrap 4.5.2.

### ISSUE THREAD

**Issue by azpro-git** [gburton/CE-Phoenix#1004]
https://github.com/gburton/CE-Phoenix/pull/1002/commits/a875fd5050f6ae77666c91841a9defa73170016a

This commit gives me in console of Firefox two Source map errors. If I revert the commit - the errors disapear.

**Comment by ecartz** [comment]
You mean:  

> Source map error: request failed with status 404  
Resource URL: https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.min.css  
Source Map URL: bootstrap.min.css.map

This seems to be a bug in the Bootstrap build on CDNJS.  

https://stackoverflow.com/a/21773495

Either they shouldn't include that line in the css file or they should deploy the map file with it.

**Comment by azpro-git** [comment]
> You mean:

yes

**Comment by ecartz** [comment]
https://github.com/cdnjs/packages/pull/412

**Comment by gburton** [comment]
As this isn't a Phoenix issue, I'll close.

**Comment by ecartz** [comment]
I believe this is fixed in CDNJS' Bootstrap 4.5.3 build, although it is still broken in 4.5.2.  Note that CE Phoenix 1.0.7.10 will switch to 4.5.3.
