### ISSUE TITLE
Undefined variable: $other_img_indicator and $other_img

### ISSUE THREAD

**Issue by beaver-man** [gburton/CE-Phoenix#1005]
there are little notices:
1:
Notice: Undefined variable: other_img_indicator in
../includes/modules/content/product_info/templates/tpl_cm_pi_gallery.php on line 55
2:
Notice: Undefined variable: other_img in
../includes/modules/content/product_info/templates/tpl_cm_pi﻿_galleryt.php on line 66

so i've fixed it by replace:

$other_img_indicator = $other_img = null;﻿

from line 25 to line 12. 

this notice is made on the advice of @raiwa
https://forums.oscommerce.com/topic/494720-kissit-image-thumbnailer-support/?do=findComment&comment=1813339

**Comment by ecartz** [comment]
https://github.com/gburton/CE-Phoenix/pull/1002/commits/1323b2a3bb736deff85e0bf7bfc4b8b1bc7a1c00
