### ISSUE TITLE
eval error in admin/modules.php

### ISSUE THREAD

**Issue by raiwa** [gburton/CE-Phoenix#1010]
Some time ago we applied the following fix in admin/modules_content.php to avoid eval error when single quotes are used in $value['value']. They need to be escaped with tep_db_input.
The same should be applied in admin/modules.php line 281-288 for the same reason:
`        if ($value['set_function']) {
          eval('$keys .= ' . $value['set_function'] . "'" . tep_db_input($value['value']) . "', '" . $key . "');");
        } else {
          $keys .= tep_draw_input_field('configuration[' . $key . ']', $value['value']);
        }
        $keys .= '<br><br>';
      }
      $keys = html_entity_decode(stripslashes(substr($keys, 0, strrpos($keys, '<br><br>'))));
`

**Comment by raiwa** [comment]
The same in admin/modules_pi.php

**Comment by ecartz** [comment]
The code already was that way in modules_pi.  But for this purpose, addslashes is better than tep_db_input.  The addslashes function is intended for PHP eval.  The tep_db_input function is intended for MySQL.  

https://github.com/gburton/CE-Phoenix/commit/7ed0f2c38da917c1e9616712c3b9f162f8961b5c

**Comment by raiwa** [comment]
O.K. But then it should be the same in all 3 files:
- admin/modules.php
- admin/modules_content.php
- admin/modules_pi.php

**Comment by ecartz** [comment]
I linked to the commit...

**Comment by raiwa** [comment]
Thanks, didn't see the link, sorry.
