### ISSUE TITLE
Add info page content hook?

### ISSUE THREAD

**Issue by zipurman** [gburton/CE-Phoenix#1011]
Just an idea. If you added a hook just after 

$page_content = $oscTemplate->getContent('info');

$OSCOM_Hooks->call('siteWide', 'infoPageContent');

Then we could start writing some add-ons that use content slugs. Like [gallery id=123]  could be added to content block and then replaced by a hook that looks for that slug and replaces it with an image gallery add-on output.

**Comment by ecartz** [comment]
Or just add a hook point inside `getContent` or `getContentModules` or both.  That would work not just on info pages but everywhere that content appears.  I almost did that a year ago but ended up doing it a different way.  

https://github.com/gburton/CE-Phoenix/blob/master/includes/system/versioned/1.0.7.6/osc_template.php

```
      if ( isset($template_page) ) {
        $template_page->build();
      }

      $OSCOM_Hooks->call('siteWide', 'getContent', $group);
      if ($this->hasContent($group)) {
        return implode("\n", $this->_content[$group]);
      }
    }

    public function getContentModules($group) {
      $results = [];

      foreach ( explode(';', MODULE_CONTENT_INSTALLED) as $m ) {
        $module = explode('/', $m, 2);

        if ( $module[0] == $group ) {
          $results[] = $module[1];
        }
      }

      $parameters = [ 'results' => &$results ];
      $OSCOM_Hooks->call('siteWide', 'getContentModules', $parameters);
      return $results;
    }
```

Please try one of those first to verify that it does what you want.

**Comment by zipurman** [comment]
Thanks, will try this ASAP and let you know ;)

**Comment by zipurman** [comment]
I tried this, however the way that the getContent() method is written, I dont know how I can override the value of $this->_content[$group] using the $OSCOM_Hooks->call('siteWide', 'getContent', $group). I am able to get the hook working, I just cant get any results in manipulating the value of the content before it is passed to the return at the end of the method.

So for example, if I want to parse the content for an area, alter the content based on whatever, and return the result to be returned by the getContent() method, how would I do that with this layout?

I did get it working like this, but I am not sure this is the nest idea:

`public function getContent($group) {
        GLOBAL $OSCOM_Hooks;

        $template_page_class = 'tp_' . $group;
      if ( class_exists($template_page_class) ) {
        $template_page = new $template_page_class();
        $template_page->prepare();
      }

      foreach ( $this->getContentModules($group) as $module ) {
        if ( class_exists($module) ) {
          $mb = new $module();

          if ( $mb->isEnabled() ) {
            $mb->execute();
          }
        }
      }

      if ( isset($template_page) ) {
        $template_page->build();
      }

      if ($this->hasContent($group)) {

          **GLOBAL $custom_content;
          $custom_content = $this->_content[$group];
          $OSCOM_Hooks->call('siteWide', 'getContent', $group);

        return implode("\n", $custom_content);**
      }
    }`

Then in my hook class I could:

`function listen_getContent($parameters) {
            if ($parameters == 'info'){
                GLOBAL $custom_content;
                foreach ( $custom_content as $key => $item ) {
                    $custom_content[$key] = str_replace( '[my-slug-text]', '<some code here>', $custom_content[$key]);
                }
            }
        }`

**Comment by zipurman** [comment]
BTW, I have also added the following to the htaccess file and to the info template to load slugs instead of having to pass infopage ids.

.htaccess add:

<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^([A-Za-z0-9]+) /info.php?pageis=$1 [L]
</IfModule>


Then /info.php add after application_top.php line:14

`    //START CUSTOM SLUG SEARCH
    if ( ! empty( $_GET["pageis"] ) ) {
        $slug = $_GET["pageis"];
        $slug = preg_replace( '/[^a-zA-Z0-9]/', '', trim( $slug ) );
        $page = tep_db_fetch_array( tep_db_query( "select * from pages where slug = '" . $slug . "'" ) );
        if ( ! empty( $page ) ) {
            $_GET['pages_id'] = $page['pages_id'];
        }
    }
    //END CUSTOM SLUG SEARCH`

**Comment by ecartz** [comment]
if ( isset($template_page) ) {
        $template_page->build();
      }

      $parameters = [
         'group' => $group,
         'content' => &$this->_content[$group],
      ];
      $GLOBALS['OSCOM_Hooks']->call('siteWide', 'getContent', $group);
      if ($this->hasContent($group)) {
        return implode("\n", $this->_content[$group]);
      }
    }

    public function getContentModules($group) {
      $results = [];

      foreach ( explode(';', MODULE_CONTENT_INSTALLED) as $m ) {
        $module = explode('/', $m, 2);

        if ( $module[0] == $group ) {
          $results[] = $module[1];
        }
      }

      $parameters = [ 'results' => &$results ];
      $GLOBALS['OSCOM_Hooks']->call('siteWide', 'getContentModules', $parameters);
      return $results;
    }

**Comment by zipurman** [comment]
Yup, that would be better for sure. 👍🏻

**Comment by zipurman** [comment]
Okay, so this will be a GAME CHANGER! So many things could be done with this!

Your example above will allow hooks to change any part of any content and add on to it, adjust it, etc. I just did some quick testing and I could use this to add much better add-ons that relying on jquery to adjust the DOM.

Thoughts on adding this to the next core release? 

This could be a highlighted feature for sure!

Also, any thoughts on adding the htaccess as I did above to add slugs that can be loaded as //url/slug?

**Comment by ecartz** [comment]
https://github.com/gburton/CE-Phoenix/commit/94eab462902c0a965777f98fcbe3cf540a897309

I do not want to change the .htaccess file.  You can of course ship a modified .htaccess with your Apps.  

Note that the other portion could be done in either a system hook or in hook_shop_info_whatever/listen_injectAppTop

**Comment by zipurman** [comment]
Fair enough. I just though that with the info pages, many people seem to thing the hook will just be available as http://example.coml/myhookpage/. Thought this might be a good add for the info pages since it is evolving and would likely make it more useful instead of ?pages_id=123

I dont have a mod that needs this, but I could create one I guess that adds this functionality as you mentioned with a hook.
