### ISSUE TITLE
Attributes - Sort Order

### ISSUE THREAD

**Issue by gburton** [gburton/CE-Phoenix#1012]
https://github.com/gburton/CE-Phoenix/commits/attrib-sort-order

The 3 commits implement this in a simple way which allows shopowner to sort Options and Values on a per language basis, which should then display appropriately (ie, ordered) as Attributes of a product. 

Tested on v1079 only. 

Open to discussion, changes etc.  
Make your voice heard if this is what you have been wanting for a while...

**Comment by skleiner** [comment]
Yes, needed and thanks

**Comment by heatherbellho** [comment]
Thank you - have had to DIY this (badly!) for years

**Comment by gburton** [comment]
Note new commit to revert the liberalisation of the Queries.

**Comment by gburton** [comment]
Oh, do also notice that this changes the layout of the admin/products_attributes page.  I have moved the elements around a bit as I *think* that the most used item (ie the bit where you add to the product) should be at the top...

Discussion needed on that change too...

**Comment by heatherbellho** [comment]
> notice that this changes the layout of the admin/products_attributes page. I have moved the elements around a bit as I _think_ that the most used item (ie the bit where you add to the product) should be at the top.
Yes, noticed and agree.

**Comment by gburton** [comment]
TY @skleiner and @heatherbellho and @ecartz  for comments - much appreciated.
I've pulled the changes in 107.10
