### ISSUE TITLE
Config use v set, static functions and autoloading

### ISSUE THREAD

**Issue by BrockleyJohn** [gburton/CE-Phoenix#1013]
Sometimes it's better to validate the concept before rewriting an addon!

I have found that while addon_class::cfg_do_something works great as a config set function using class autoloading, currently it just doesn't get executed as a use function - however were I to set it as addon_class->cfg_do_something (and not define it as static) then that gets handled in admin/configuration.php

Can we just change "function_exists" to "is_callable" here or is there more to it?

https://github.com/gburton/CE-Phoenix/blob/6bc7c69219a77291a0d3aad2d6a0f3956307cdfd/admin/configuration.php#L72

**Comment by ecartz** [comment]
I'm unclear.  Have you tried changing it to `is_callable`?  Does it work?  

I notice that in admin/modules.php we don't check callability at all.  Perhaps we should just remove the check here to match what is done there.  Then if it's not callable, it will error rather than silently failing.  

```
                $use_function = $configuration['use_function'];
                if (preg_match('/->/', $configuration['use_function'])) {
                  $class_method = explode('->', $use_function);
                  if (!is_object(${$class_method[0]})) {
                    ${$class_method[0]} = new $class_method[0]();
                  }
                  $use_function = [${$class_method[0]}, $class_method[1]];
                }
                call_user_function($use_function, $configuration['configuration_value']);
```

**Comment by BrockleyJohn** [comment]
Sorry - yes, it works fine with is_callable instead. 
I assume it's silent fail by design so you don't kill admin with a dodgy addon.
