### ISSUE TITLE
options related sql errors in 1.0.7.10 branch

### ISSUE THREAD

**Issue by raiwa** [gburton/CE-Phoenix#1016]
On a server installation under PHP 7.3  I get the following error in checkout_shipping.php if a product with option is in the cart:

`1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'option, poval.products_options_values_name AS value, pa.options_id AS opti' at line 2

SELECT popt.products_options_name AS option, poval.products_options_values_name AS value, pa.options_id AS option_id, pa.options_values_id AS value_id, pa.price_prefix AS prefix, pa.options_values_price AS price FROM products_options popt INNER JOIN products_attributes pa ON pa.options_id = popt.products_options_id INNER JOIN products_options_values poval ON pa.options_values_id = poval.products_options_values_id AND popt.language_id = poval.language_id WHERE pa.products_id = 4 AND pa.options_id = 1 AND pa.options_values_id = 1 AND popt.language_id = 1`

Orders with products without options are going through, but editing them in admin/orders.php throws this error:

`1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'option, products_options_values AS value, price_prefix AS prefix, optio' at line 2

SELECT products_options as option, products_options_values AS value, price_prefix AS prefix, options_values_price AS price FROM orders_products_attributes WHERE orders_id = 1 AND orders_products_id = 1`

Curious thing is that on my local installation under XAMPP, these errors do not show up.

Note that this is a fresh unmodified installation made with the 1.0.7.10 Installer.

**Comment by ecartz** [comment]
Try putting backticks around option.  I.e. 

```
SELECT
   popt.products_options_name AS `option`,
   poval.products_options_values_name AS value,
   pa.options_id AS option_id, pa.options_values_id AS value_id,
   pa.price_prefix AS prefix, pa.options_values_price AS price
 FROM
```

If that fixes it, then it's probably a MySQL thing.  Compare versions and configuration between the server and local installations.

**Comment by raiwa** [comment]
Adding backticks fixes the error.
Local versions (no error):

WINNT
--
Database | MySQL 5.5.5-10.1.38-MariaDB
HTTP Server | Apache/2.4.38 (Win64) OpenSSL/1.1.1a PHP/7.3.2
PHP Version | 7.3.2 (Zend 3.3.2)

Server versions (shows errors):
Server OS | Linux 3.10.0-862.3.2.el7.x86_64
Database | MySQL 5.7.30-33-log
HTTP Server | Apache
PHP Version | 7.3.22 (Zend 3.3.22)


Another issue:
Updating the order status in admin/orders.php throws these errors:
 
`Warning: Use of undefined constant EMAIL_TEXT_COMMENTS_UPDATE - assumed 'EMAIL_TEXT_COMMENTS_UPDATE' (this will throw an Error in a future version of PHP) in /web/htdocs/www.oscaddons.com/home/phoenix_test/includes/modules/notifications/n_update_order.php on line 22

Notice: Undefined index: oscTemplate in xxxxxxxxxxphoenix_test/includes/modules/notifications/n_update_order.php on line 28

Fatal error: Uncaught Error: Call to a member function map_to_template() on null in /xxxxxxxxxxxxxx/phoenix_test/includes/modules/notifications/n_update_order.php:28 Stack trace: #0 /xxxxxxxxxxxxxxxxxxxxxxxxxx/phoenix_test/admin/includes/functions/general.php(1110): n_update_order->notify(Array) #1 /xxxxxxxxxxxxxxxxxxxxxxxx/phoenix_test/admin/orders.php(48): tep_notify('update_order', Array) #2 {main} thrown in /xxxxxxxxxxxxxxxx/phoenix_test/includes/modules/notifications/n_update_order.php on line 28`

**Comment by ecartz** [comment]
Perhaps it is a MySQL/MariaDB issue.  Since I don't think that we are prepared to require MariaDB over MySQL, I just added the backticks.  

I think that I have fixed the notification module issues.

**Comment by raiwa** [comment]
I had to add the backticks also in:
\includes\system\versioned\1.0.7.10\database_order_builder.php line 18
