### ISSUE TITLE
Update UI icons and card list in account card modules

### ISSUE THREAD

**Issue by raiwa** [gburton/CE-Phoenix#1017]
I found 2 things in the braintree and sagepay account card modules:
- the delete button in the card list shows missaligned if more than 1 card is listed
- ui icons are still used in the buttons

I have this already fixed for the stripe card module.
Shall I push the fix for braintree and sagepay?

**Comment by ecartz** [comment]
Pushing into 1.0.7.10 makes sense to me.  

@gburton Thoughts?

**Comment by gburton** [comment]
@raiwa  yes please, that would be great to branch 1.0.7.10.  TY

**Comment by ecartz** [comment]
Since this is pushed into 1.0.7.10, I'm going to close it.  This isn't a problem that you are experiencing, so I don't think you really need us to notify you when it is released.  

Thanks for your help.
