### ISSUE TITLE
minor notice errors in admin/categories.php

### ISSUE THREAD

**Issue by raiwa** [gburton/CE-Phoenix#1020]
When creating a new product from zero, these notice errors are thrown:

> [Thu Oct 29 19:18:30.177869 2020] [php7:notice] [pid 9888:tid 1900] [client ::1:64063] PHP Notice:  Trying to access array offset on value of type null in C:\\xampp_7.4.11\\htdocs\\xxxxxxxxxxxxxx\\admin\\includes\\functions\\general.php on line 548, referer: http://localhost/xxxxxxxxxxxxxx/admin/categories.php?cPath=1  
> [Thu Oct 29 19:18:30.177869 2020] [php7:notice] [pid 9888:tid 1900] [client ::1:64063] PHP Notice:  Trying to access array offset on value of type null in C:\\xampp_7.4.11\\htdocs\\xxxxxxxxxxxxxx\\admin\\includes\\functions\\general.php on line 1371, referer: http://localhost/xxxxxxxxxxxxxx/admin/categories.php?cPath=1  
> [Thu Oct 29 19:18:30.193451 2020] [php7:notice] [pid 9888:tid 1900] [client ::1:64063] PHP Notice:  Trying to access array offset on value of type null in C:\\xampp_7.4.11\\htdocs\\xxxxxxxxxxxxxx\\admin\\includes\\functions\\general.php on line 548, referer: http://localhost/xxxxxxxxxxxxxx/admin/categories.php?cPath=1
> [Thu Oct 29 19:18:30.193451 2020] [php7:notice] [pid 9888:tid 1900] [client ::1:64063] PHP Notice:  Trying to access array offset on value of type null in C:\\xampp_7.4.11\\htdocs\\xxxxxxxxxxxxxx\\admin\\includes\\functions\\general.php on line 1371, referer: http://localhost/xxxxxxxxxxxxxx/admin/categories.php?cPath=1
> [Thu Oct 29 19:18:30.193451 2020] [php7:notice] [pid 9888:tid 1900] [client ::1:64063] PHP Notice:  Trying to access array offset on value of type null in C:\\xampp_7.4.11\\htdocs\\xxxxxxxxxxxxxx\\admin\\includes\\functions\\general.php on line 548, referer: http://localhost/xxxxxxxxxxxxxx/admin/categories.php?cPath=1
> [Thu Oct 29 19:18:30.193451 2020] [php7:notice] [pid 9888:tid 1900] [client ::1:64063] PHP Notice:  Trying to access array offset on value of type null in C:\\xampp_7.4.11\\htdocs\\xxxxxxxxxxxxxx\\admin\\includes\\functions\\general.php on line 1371, referer: http://localhost/xxxxxxxxxxxxxx/admin/categories.php?cPath=1

**Comment by BrockleyJohn** [comment]
How do you decide which database corruptions to handle and which not?

**Comment by raiwa** [comment]
This is from my test shop which's database is ok.

**Comment by BrockleyJohn** [comment]
OK - sorry then I misunderstood! Not adding product with id 0 but adding first product in clean db?

**Comment by raiwa** [comment]
Not necessary first product in clean db. "New product" from zero, not modifying an existing product ("Edit").

**Comment by ecartz** [comment]
What version is this?  In the current version (1.0.7.10), line 1371 is blank.

**Comment by raiwa** [comment]
1.0.7.9

**Comment by raiwa** [comment]
For 1.0.7.10:
`[Fri Oct 30 15:37:09.125613 2020] [php7:notice] [pid 17044:tid 1868] [client ::1:51328] PHP Notice:  Trying to access array offset on value of type null in C:\\xampp_7.4.11\\htdocs\\xxxxxxxxxx\\admin\\includes\\functions\\general.php on line 897, referer: http://localhost/xxxxxxxxxx/admin/categories.php
[Fri Oct 30 15:37:09.125613 2020] [php7:notice] [pid 17044:tid 1868] [client ::1:51328] PHP Notice:  Trying to access array offset on value of type null in C:\\xampp_7.4.11\\htdocs\\xxxxxxxxxx\\admin\\includes\\functions\\general.php on line 898, referer: http://localhost/xxxxxxxxxx/admin/categories.php
[Fri Oct 30 15:37:09.125613 2020] [php7:notice] [pid 17044:tid 1868] [client ::1:51328] PHP Notice:  Trying to access array offset on value of type null in C:\\xampp_7.4.11\\htdocs\\xxxxxxxxxx\\admin\\includes\\functions\\general.php on line 548, referer: http://localhost/xxxxxxxxxx/admin/categories.php
[Fri Oct 30 15:37:09.135578 2020] [php7:notice] [pid 17044:tid 1868] [client ::1:51328] PHP Notice:  Trying to access array offset on value of type null in C:\\xampp_7.4.11\\htdocs\\xxxxxxxxxx\\admin\\includes\\functions\\general.php on line 1399, referer: http://localhost/xxxxxxxxxx/admin/categories.php
[Fri Oct 30 15:37:09.135578 2020] [php7:notice] [pid 17044:tid 1868] [client ::1:51328] PHP Notice:  Trying to access array offset on value of type null in C:\\xampp_7.4.11\\htdocs\\xxxxxxxxxx\\admin\\includes\\functions\\general.php on line 548, referer: http://localhost/xxxxxxxxxx/admin/categories.php
[Fri Oct 30 15:37:09.135578 2020] [php7:notice] [pid 17044:tid 1868] [client ::1:51328] PHP Notice:  Trying to access array offset on value of type null in C:\\xampp_7.4.11\\htdocs\\xxxxxxxxxx\\admin\\includes\\functions\\general.php on line 1399, referer: http://localhost/xxxxxxxxxx/admin/categories.php
`

**Comment by gburton** [comment]
I believe we just need to do a ?? null on the return from the relevant functions...

**Comment by ecartz** [comment]
I think it would be better to not call them in that case.  We're doing six? database calls that are unnecessary -- we know that the not yet existing product won't have values.  So we should just check if there is a product ID before we attempt to call the functions.  

And frankly, if I had my druthers, we'd rip out all those functions and toss them in favor of one query that got all six values.  It's silly that we are making six database calls to the same table.  It was a hacky solution for the second column.  For six, it's getting ridiculous.  

The only real complicating part is that I haven't looked at this code recently and I'm not sure where these are being called.  Not the lines in general.php but the lines in categories.php that are calling those functions.  

I would rather not add ?? null because this situation should generate a notice if it happens in any situation but this one.  So I think it would be better to simply not call those functions when this is expected to happen.  Then if we get notices we can pay attention to them as indicating that something is broken.  I think this is what John meant when he said, "How do you decide which database corruptions to handle and which not?"

**Comment by raiwa** [comment]
In some places like for name and description it's already secured on that way:
`(empty($pInfo->products_id) ? '' : tep_get_products_description($pInfo->products_id, $languages[$i]['id'])`

**Comment by gburton** [comment]
Let's leave these minor things for now.  When we eventually get a product class, we can look at centralising and fixing a lot of things.
