### ISSUE TITLE
Contributing to Phoenix

### ISSUE THREAD

**Issue by PhilterPaper** [gburton/CE-Phoenix#1025]
I have a number of things I'd like to contribute to Phoenix, if you'll take them. I see that you want such things to be first discussed in an Issue before a PR will even be considered (a perfectly reasonable thing), and you want a solid Test Plan. For the latter, what are you looking for in the way of a test plan? Does this include manual and automated testing? Do you have some examples somewhere of what you want to see? Obviously I test code changes, but some things you might require more rigor for.

I have a lot of things, and can break them down into the following PRs:

- product weight more numeric places to permit a wider range of weights. I had a client who sold products weighing from a few grams to tens of kilograms, and the default field size is too restrictive to cover the full range.
- tare weight calculation. a) clarify the DB entries for the percentage and minimum fields, and how they relate, in terms that a business person can understand. b) ensure that if the total product weight is 0 (nothing physically shipped), the tare (packaging) weight is 0 so the customer isn't charged for shipping.
- database True and False fields, update to use selection dropdown instead of (in many cases) requiring 'True' or 'False' to be typed in exactly.
- many typos, grammatical errors, spelling errors, and unclear text to be fixed in both DB configuration entries _and_ in language files. Plus, remove extra spaces in text so that it's possible to **search** for a given string in the files or DB.
- .htaccess files add commentary on _why_ certain things are being done, and what to do when it doesn't work. For example, why `Options -Indexes` and what are the alternatives if your host doesn't permit `Options`. Remember that these are business people trying to get a tool to work, not computer experts.
- URLs updated to current, including https for all.
- DB change checkout allowed on no stock default to 'No', Canada address format is wrong, update several new countries.
- maybe a few more random things

There were a number of things I did for clients on older osC CE releases, but haven't updated yet for Phoenix. Not all of them may be needed, or even feasible, any more:

- there were a lot of 777 permissions hard coded into the code, which is a terrible thing to do. You need to grant minimal permissions. Whether this can be automated or will require user intervention, I don't know. If this is something that confuses even seasoned hackers, imagine how it is for a business person!
- much easier to read bulleted category type lists (e.g., manufacturers, categories), but this may not be needed any more. There is no longer a column_left.php.
- store-provided HTML should not be stripped of tags (it should be trustworthy), except possibly for a teaser. In that case, it might be better to provide separate teaser text.
- I _think_ the special/sale price is no longer confused with the regular price, but I'll keep an eye open for it.
- make "Please Select" the default for all selection lists, unless you pick a specific entry to be the default.

**Comment by gburton** [comment]
> product weight more numeric places to permit a wider range of weights. I had a client who sold products weighing from a few grams to tens of kilograms, and the default field size is too restrictive to cover the full range.

That type of client would be 1 in 1000 or more.  However, there is merit in increasing the field vales.

**Comment by gburton** [comment]
> * tare weight calculation. a) clarify the DB entries for the percentage and minimum fields, and how they relate, in terms that a business person can understand. b) ensure that if the total product weight is 0 (nothing physically shipped), the tare (packaging) weight is 0 so the customer isn't charged for shipping.

A.  No.  They are already easy to understand.
B.  This has merit.  I have never tested this scenario.

**Comment by gburton** [comment]
> * database True and False fields, update to use selection dropdown instead of (in many cases) requiring 'True' or 'False' to be typed in exactly.

Where in Admin (presumably when dealing with modules) does one have to literally write True (or False) ?  
Off the top of my head I cannot remember.

**Comment by gburton** [comment]
> * many typos, grammatical errors, spelling errors, and unclear text to be fixed in both DB configuration entries _and_ in language files. Plus, remove extra spaces in text so that it's possible to **search** for a given string in the files or DB.

No.

**Comment by gburton** [comment]
> * .htaccess files add commentary on _why_ certain things are being done, and what to do when it doesn't work. For example, why `Options -Indexes` and what are the alternatives if your host doesn't permit `Options`. Remember that these are business people trying to get a tool to work, not computer experts.

No.  Reasoning is on the forum in response to your previous posting.

**Comment by gburton** [comment]
> * URLs updated to current, including https for all.

Which URLs are incorrect ?

**Comment by gburton** [comment]
> * DB change checkout allowed on no stock default to 'No'

Why?

> Canada address format is wrong

This has merit.

>update several new countries

Ditto

**Comment by gburton** [comment]
> what are you looking for in the way of a test plan

That any resulting code change is tested to the best of ones ability.

**Comment by PhilterPaper** [comment]
> > * tare weight calculation. a) clarify the DB entries for the percentage and minimum fields, and how they relate, in terms that a business person can understand. 
> 
> A. No. They are already easy to understand.

Actually, they're very confusing to someone in the business world.
```
                  Current text                                       My revision
Package Tare Weight:                              Minimum Tare Weight:
  What is the weight of typical packaging of        What is the MINIMUM Tare Weight? (for your
    small to medium packages?                         smallest package). 0 will be used if no
                                                      physical goods shipped.
Larger packages - percentage increase:            Tare Weight calculation:
   For 10% enter 10                                Tare Weight as a percentage of product 
                                                     weight (e.g., 10 for 10%), subject to
                                                     minimum tare weight.
```
I had clients who where very frustrated that they could not get shipping weights to come out correctly. After tracing through the code, I figured out how these fields were _really_ applied, and revised the text to clarify it. This also led to discovering the (B) error where the minimum tare weight was applied even if no physical product was shipped.

**Comment by PhilterPaper** [comment]
> >  database True and False fields, update to use selection dropdown instead of (in many cases) requiring 'True' or 'False' to be typed in exactly.
> 
> Where in Admin (presumably when dealing with modules) does one have to literally write True (or False) ?
> Off the top of my head I cannot remember.

- (configuration) Enable Address Book ID module
- (configuration) Enable Traditional Short Name module
- (configuration) Enable Two Part Name module
- (configuration) Enable Two Part Sortable Name module
- (configuration) Enable Email Username module
- (configuration) Enable Identifier module
- (configuration) Enable Traditional Address module

I think that's all of them. BTW, I've even considered making a wrapper function `tep_selectTF()` as the update function for all True/False entries (would entail changing a few 'true/false' to 'True/False' or vice-versa, or two separate versions of the select), just to simplify maintaining the DB.

**Comment by PhilterPaper** [comment]
> > many typos, grammatical errors, spelling errors, and unclear text to be fixed in both DB configuration entries _and_ in language files. Plus, remove extra spaces in text so that it's possible to **search** for a given string in the files or DB.
> 
> No.

- Welcome **on** _store name_ instead of Welcome **to**
- misuse of 'setup' (noun) instead of 'set up' (verb)
- misspelling of 'e.g.' as 'eg', or swapping 'i.e.' and 'e.g.'
- **Amount** of products to list _instead of_ **Number** of products

...and many more. I think there would be much more uptake of Phoenix (and possibly more money flowing to you) if it looked more polished and professional. I know that _I_ would be hesitant to entrust my business to a software package that looked like it was created by a group of First Grade English class dropouts!

Look, I'm willing to do the work for you and create the PR for you to pull. Why the opposition to making Phoenix look polished and professional, like it was put out by a large software house, employing real editors and real proofreaders? It can't do anything but _help_ the situation.

Regarding the extra spaces in text, I _know_ that the browser will squeeze them out. The problem is when a shop owner (usually not a computer professional) wants to find some text in the DB or files, in order to modify it for their purposes, and can't match something like "...not a valid file. Leave..." (one space at end of sentence) because the actual text in the file or DB is "...not a valid file.  Leave...". (two spaces at end of sentence). Anyone (business person or computer professional) searching for text in osC has encountered this and been very frustrated.

**Comment by gburton** [comment]
@ecartz - any particular reason why the CD modules use a textual input for True/False ?  
BTW I am not bothered that they do as it's not exactly onerous to have to write a word instead of clicking an option.

**Comment by gburton** [comment]
> It can't do anything but _help_ the situation.

No.  Thank you.

**Comment by gburton** [comment]
> Actually, they're very confusing to someone in the business world.

No.  Thank You.
Your revision is more confusing than the orginal.

**Comment by PhilterPaper** [comment]
> > .htaccess files add commentary on _why_ certain things are being done, and what to do when it doesn't work. For example, why `Options -Indexes` and what are the alternatives if your host doesn't permit `Options`. Remember that these are business people trying to get a tool to work, not computer experts.
> 
> No. Reasoning is on the forum in response to your previous posting.

Well, I think you're forgetting that most of the people trying to set up a Phoenix store are business people, not computer professionals. They generally need some extra help (in the form of more verbose explanations in the .htaccess comments) about what's going on (_why_) and what their choices are if something fails (e.g., `Options` directive not allowed on their server). If they go to their host support or a local professional, they're likely to be told: "osCommerce? Ha! That thing is ancient, at least 15 years behind the times. You should install something that's up-to-date and actually supported!"

I wonder how many osC and Phoenix users have been lost because they couldn't get through the installation successfully, and quit and went to some other package? What's the harm in our being a little more helpful and instructive to them?

**Comment by PhilterPaper** [comment]
> > URLs updated to current, including https for all.
> 
> Which URLs are incorrect ?

- feeds.feedburner.com
- facebook.com
- twitter.com
- oscommerce.com

That's not counting all the oscommerce copyright notices in most files. There might be a few more, but those are the ones that I recall off the top of my head. Sure, they'll redirect to https, but why not look better to a user or shop owner by having the correct URL in the first place?

**Comment by PhilterPaper** [comment]
> > DB change checkout allowed on no stock default to 'No'
> 
> Why?

I feel  that this one is a booby-trap laid for an unsuspecting store owner. _By default,_ Phoenix allows a customer to check out (note: not "checkout") even if insufficient stock, which can cause problems for the store if it will be a while before (or, if ever) inventories are restored. I think the default should be 'no' ('false'), so that the store owner has to deliberately set it to 'true' while (presumably) knowing full well what they're getting into (having to issue rain checks, etc.).

**Comment by gburton** [comment]
> I feel that this one is a booby-trap laid for an unsuspecting store owner.

It's a setting that some shopowners will want "on" and some "off".  
Do we really care which setting comes as default;  no we don't, so we will leave it as is.

**Comment by gburton** [comment]
> why not look better to a user or shop owner by having the correct URL in the first place

It's unimportant.  Let's leave them as is for now.

**Comment by gburton** [comment]
> Well, I think you're forgetting that most of the people trying to set up a Phoenix store are business people, not computer professionals.

When these "business people" realise that their business is being subsidised by a handful of other businesses...is when I take their view into account.  

> I wonder how many osC and Phoenix users have been lost because they couldn't get through the installation successfully

If someone cannot get through an extremely simple installation that takes 5 minutes manually, or 30 seconds via control panel...then they need extreme hand-holding and that is a service they should be paying for.

I think that you need to recognise that some shopowners need extreme hand-holding and some like to poke and prod.  We can cater to both with the way that we are going in terms of core code and other "behind the scenes" things.

**Comment by PhilterPaper** [comment]
> > Well, I think you're forgetting that most of the people trying to set up a Phoenix store are business people, not computer professionals.
> 
> When these "business people" realise that their business is being subsidised by a handful of other businesses...is when I take their view into account.

In the meantime, we need to keep installation and configuration confined to the high priesthood. We can't afford to make it clear and relatively easy for intelligent people otherwise not trained in computers to deal with most situations.
 
> > I wonder how many osC and Phoenix users have been lost because they couldn't get through the installation successfully
> 
> If someone cannot get through an extremely simple installation that takes 5 minutes manually, or 30 seconds via control panel...then they need extreme hand-holding and that is a service they should be paying for.
> 
> I think that you need to recognise that some shopowners need extreme hand-holding and some like to poke and prod. We can cater to both with the way that we are going in terms of core code and other "behind the scenes" things.

What is a shop owner supposed to do when they get a cryptic error message about disallowed commands such as `Options` or disallowed write and/or execute permissions due to `chmod 777`? Most will have no idea what to do. They will have to go to a paid professional (or their host's tech support), who will advise them to ditch osC/Phoenix right away. Too bad a few lines of explanation are too high a price of to pay for retaining osC/Phoenix users.

**Comment by ecartz** [comment]
> Anyone (business person or computer professional) searching for text in osC has encountered this and been very frustrated.

Well, except those business people and computer professionals who were taught by their typing teachers that there should always be two spaces after a period (or colon) so as to separate it from those other things that do not (commas and semi-colons).  We get really frustrated when we go searching and someone has left off the space due, perhaps, to not taking typing classes and therefore not knowing how to do it correctly.  Or for that matter, when we try to [find the sentence breaks at a glance](https://link.springer.com/article/10.3758/s13414-018-1527-6) and keep missing them because there's only one space where there should be two.  

> By default, Phoenix allows a customer to check out (note: not "checkout") even if insufficient stock, which can cause problems for the store if it will be a while before (or, if ever) inventories are restored.

What about the other people?  Those who do not track stock?  Your way, they would be silently losing customers for ages.  Now that's a trap.  

Meanwhile, people who want to track stock but miss the configuration will know to look for it whenever they get their first out of stock purchase attempt.  

Which is better?  Silently failing to do the right thing forever?  Or doing an obvious wrong thing once?  Not tracking stock is by far the safer default.  Because people will be able to see when it fails.

**Comment by ecartz** [comment]
> any particular reason why the CD modules use a textual input for True/False ?

TY.  https://github.com/gburton/CE-Phoenix/commit/61b9649d90643d052cd3e22b1067c72af209360d

**Comment by gburton** [comment]
I like how you constantly refer to "computer professionals" and "business people".  Yet call this work:

"created by a group of First Grade English class dropouts"
and
"crappy looking"

Got it now?  I am not interested in further debate on pedantry about words and grammar. 
Some things are deliberately incorrect for a reason.

Anything in the actual code (ie what would be very difficult for one of your "computer professionals" or "business people" to change) I am interested in making correct.

**Comment by PhilterPaper** [comment]
I can see that this is going to go nowhere. I shall join the ranks of those advising osC/Phoenix users to flee to another platform as quickly as they can. So long, suckers! Good-bye for good.

**Comment by gburton** [comment]
Classy.
