### ISSUE TITLE
Deprecated get_browser_language

### ISSUE THREAD

**Issue by yenoyen** [gburton/CE-Phoenix#1028]
1.0.7.12 updated 2020-12-11
PHP 7.4.13

**admin** error after the installation

Deprecated: The get_browser_language function has been deprecated. in /data/web/virtuals/USERID/virtual/www/subdom/eshop/includes/system/versioned/1.0.7.other/1.0.7.12/language.php on line 184

Warning: Cannot modify header information - headers already sent by (output started at /data/web/virtuals/USERID/virtual/www/subdom/eshop/includes/system/versioned/1.0.7.other/1.0.7.12/language.php:184) in /data/web/virtuals/USERID/virtual/www/subdom/eshop/sprava/includes/functions/general.php on line 36

**Comment by ecartz** [comment]
Closing, as the commit should fix this and it only appeared in 1.0.7.12, so we don't need to wait for a merge.
