### ISSUE TITLE
Undefined variable: PHP_SELF

### ISSUE THREAD

**Issue by yenoyen** [gburton/CE-Phoenix#1029]
1.0.7.12 updated 2020-12-11
PHP 7.4.13

**catalog** works, but another notice added after every refresh of the page

Notice: Undefined variable: PHP_SELF in /data/web/virtuals/261546/virtual/www/subdom/eshop/includes/classes/navigation_history.php on line 30

Notice: Undefined variable: PHP_SELF in /data/web/virtuals/261546/virtual/www/subdom/eshop/includes/classes/navigation_history.php on line 30

**Comment by ecartz** [comment]
https://github.com/gburton/CE-Phoenix/commit/bb682e50f321a628708fa04e3e98b8973e5f01fb

**Comment by ecartz** [comment]
Closing, as the commit should fix this and this only appeared in 1.0.7.12, so we don't have to wait for a merge.
