### ISSUE TITLE
Minor usability issue on payment selection

### ISSUE THREAD

**Issue by BrockleyJohn** [gburton/CE-Phoenix#1034]
Only apparent when you have payment modules that have their own radio buttons on checkout_payment.

Clicking on payment selection rows toggles the module selection radiobuttons but has the side effect of clearing any other radiobuttons in the table.
![2021-01-19 (1)](https://user-images.githubusercontent.com/1625498/105074275-0d46f580-5a80-11eb-8c9d-2e173c426fe9.png)

Fix is to be more selective in jquery:
https://github.com/gburton/CE-Phoenix/compare/master...BrockleyJohn:ht_table_click_jquery

**Comment by gburton** [comment]
TY
