### ISSUE TITLE
Html tags corrupted in product and category descriptions

### ISSUE THREAD

**Issue by BrockleyJohn** [gburton/CE-Phoenix#1036]
`Text::prepare`
garbles tags in the textual description fields of products and categories (and possibly elsewhere) - and less importantly, line breaks.
https://github.com/gburton/CE-Phoenix/blob/977930836be31abce328f44f48808d09a263cce0/admin/categories.php#L73
https://github.com/gburton/CE-Phoenix/blob/977930836be31abce328f44f48808d09a263cce0/admin/categories.php#L236

via the sanitize method in the Text class
e.g. 

> _h3_Combined Search and Category List Navbar Dropdown - the Find Menu_/h3_ _p_Free up page space by putting the search bar and categories box inside a navbar dropdown._/p_

**Comment by ecartz** [comment]
That was already reported:  https://forums.oscommerce.com/topic/496605-v10713-questions-comments-concerns/?page=2&tab=comments#comment-1819081

https://github.com/gburton/CE-Phoenix/commit/71da053c689ca7c61b2955dc710a8c4a14b661f2
https://github.com/gburton/CE-Phoenix/commit/eed99c3f16d89711fb337e0b854ee7bdb800a87a

Please read the existing reports before making new ones.

**Comment by BrockleyJohn** [comment]
Did go through the thread but must have missed that one. 
Also checked latest 1.0.7.14 
[https://github.com/gburton/CE-Phoenix/blob/1.0.7.14/admin/categories.php](https://github.com/gburton/CE-Phoenix/blob/1.0.7.14/admin/categories.php)
to see if it was fixed without a report.
Have those changes got overwritten or am I looking in the wrong place? The graphic view on sourcetree shows it as a direct descendant of that commit.

**Comment by BrockleyJohn** [comment]
Never mind - found the other commit  [6c955b4 ](https://github.com/gburton/CE-Phoenix/commit/6c955b462be03fb23cd1fe1ed7406f71dd5c54c2) where the method called reverts to the original in admin categories...
