### ISSUE TITLE
Additional hook request for admin categories panel manipulation

### ISSUE THREAD

**Issue by BrockleyJohn** [gburton/CE-Phoenix#1037]
I've some addons that put stuff in the focus panel (the grey bit on the side of lists) in admin categories. I've done some quick tests and I think a single hook here (just before the common box creation) would work for all of them:

https://github.com/gburton/CE-Phoenix/blob/977930836be31abce328f44f48808d09a263cce0/admin/categories.php#L1184

perhaps
` $OSCOM_Hooks->call('categories', 'panel');`

for manipulating the contents before output.

**Comment by ecartz** [comment]
Why can't you use categories.infoBox ?

**Comment by BrockleyJohn** [comment]
Just the usual reason - ignorance :-)
