### ISSUE TITLE
reviews write missing in page selection

### ISSUE THREAD

**Issue by raiwa** [gburton/CE-Phoenix#1043]
It seems the page selection methods do not read the pages in: ext/modules/content/
Noticeable in the Table Row Click jQuery Header Tag module's pages list.

**Comment by gburton** [comment]
For testing (as I have not tested this..

https://github.com/gburton/CE-Phoenix/blob/master/includes/system/versioned/1.0.5.6/page_selection.php#L35-L49

to:

`
$files_array = [];
      
// main files
foreach (new DirectoryIterator(DIR_FS_CATALOG) as $file) {
  if ($file->isFile() && ($file->getExtension() == 'php')) {
    $files_array[] = $file->getFilename();
  }
}
      
// ext files
$dir = new RecursiveDirectoryIterator(DIR_FS_CATALOG . 'ext/modules/content/');
$iterator = new RecursiveIteratorIterator($dir);

foreach ($iterator as $file) {
  if ($file->isFile() && ($file->getExtension() == 'php')) {
    $files_array[] = basename($file->getPathname());
  }
}
      
$files_array = array_unique($files_array);
`

**Comment by raiwa** [comment]
Seems to work as expected. Tested with my store tax below price module and core Table Row Click jQuery ht module.

**Comment by gburton** [comment]
TY

https://github.com/gburton/CE-Phoenix/commit/cbb150bbed8da39fb59c11493206d5bc27638867
