### ISSUE TITLE
Javascript errors running BrainTree payments

### ISSUE THREAD

**Issue by scottcwilson** [gburton/CE-Phoenix#764]
Currently the function for capturing card details is firing before jQuery is loaded. 

![image](https://user-images.githubusercontent.com/4391638/62422437-bdece980-b680-11e9-82c7-fd0529905301.png)

**Comment by scottcwilson** [comment]
I have a small PR for this if you'll take it.

**Comment by gburton** [comment]
Braintree App is due to be updated in the very near future, per SCA etc.  I suspect this will be addressed at that time.  TY.
