### ISSUE TITLE
When associated _WAY define is empty, don't add brackets

### ISSUE THREAD

**Issue by scottcwilson** [gburton/CE-Phoenix#766]
Right now, Flat Rate is presented in the order total line items as 

Flat Rate ():	

since MODULE_SHIPPING_FLAT_TEXT_WAY is empty.  The code should test for this condition and if it's true, not add brackets.

**Comment by gburton** [comment]
I thought that was changed some time back...maybe on a branch then never pulled in.

**Comment by scottcwilson** [comment]
Nope, just updated my repo and it's still there. LMK if you want a PR.

**Comment by gburton** [comment]
Sure thing, PR it.

**Comment by gburton** [comment]
1.0.1.3
