### ISSUE TITLE
Show database name on Admin->Tools->Server Info

### ISSUE THREAD

**Issue by scottcwilson** [gburton/CE-Phoenix#767]
It's useful to see the name of the database being used (i.e. DB_DATABASE) so you don't have to pull the configure.php file if you're doing work on a site.  (This ensures you are looking at the right one if multiple dbs appear in phpMyAdmin.)

**Comment by gburton** [comment]
Would it be simpler to write a security check (info) module ?

**Comment by scottcwilson** [comment]
I am proposing a one line change to server_info.php.  Doesn't get much simpler.

**Comment by gburton** [comment]
We dont do core code changes if they're not needed.

**Comment by scottcwilson** [comment]
It's pretty unintuitive to look at Security Checks for the database name.  Don't you think this would be useful when you're looking at a client's site in admin, but when you open phpMyAdmin they have 10 databases?

**Comment by gburton** [comment]
No, shopowners dont need to know this data, and pro's know precisely where to find this data in 10 seconds.  

Let's forget this one.
