### ISSUE TITLE
Deprecated DIR_WS_CATALOG_IMAGES

### ISSUE THREAD

**Issue by BecRoM** [gburton/CE-Phoenix#773]
I find "DIR_WS_CATALOG_IMAGES" on catalog/includes/modules/boxes/bm_card_acceptance.php

`  function bm_card_acceptance_show_logos($text) {
    $output = '';
    if ( !empty($text) ) {
      $output = '<ul style="list-style-type: none; margin: 0; padding: 5px; margin-bottom: 10px;">';
      foreach (explode(';', $text) as $card) {
        $output .= '<li style="padding: 2px;">' . tep_image(DIR_WS_CATALOG_IMAGES . 'card_acceptance/' . basename($card), basename($card)) . '</li>';
      }
      $output .= '</ul>';
    }
    return $output;
  }`

It should be:
`  function bm_card_acceptance_show_logos($text) {
    $output = '';
    if ( !empty($text) ) {
      $output = '<ul style="list-style-type: none; margin: 0; padding: 5px; margin-bottom: 10px;">';
      foreach (explode(';', $text) as $card) {
        $output .= '<li style="padding: 2px;">' . tep_image('images/'card_acceptance/' . basename($card), basename($card)) . '</li>';
      }
      $output .= '</ul>';
    }
    return $output;
  }`

Regards

**Comment by gburton** [comment]
TY.

This is an admin side usage, so it should be as it is.  
Usage of DIR_WS_CATALOG_IMAGES in this case is correct.
