### ISSUE TITLE
Move box list creation out of language files, allow extension without core change

### ISSUE THREAD

**Issue by scottcwilson** [gburton/CE-Phoenix#775]
Implementation of a concept discussed here: 
https://forums.oscommerce.com/topic/493826-adding-to-the-information-sidebox-in-phoenix/?tab=comments#comment-1792609

Allow modders to add entries to boxes (information box in this case) without modifying core files.  Also moves filenames into the core so users wishing to change language files don't see filenames or arrays, just a list of defines.

**Comment by gburton** [comment]
I'm not liking it, sorry.

Removes flexibility 
- new page (amend 1 language file, done)
- remove page (amend same language file, done)

Adds in inflexibility
- new page (ok)
- remove page (impossible without knowledge of php)

Thank you for concept code.  I simply don't see the point of combining a core array and a user made array.  Why not just have it all as one array (like it is at the moment).

**Comment by scottcwilson** [comment]
OK hang on - let me give it one more shot.

**Comment by gburton** [comment]
Scott - many thanks - don't spend another minute on it.  

It's a solution that is looking for a problem.  Language files are made to be changed.

**Comment by scottcwilson** [comment]
OK.  I thought this could help avoid file changes but if you don't like it we can move on.
