### ISSUE TITLE
Guard against CC_NUMBER_MIN_LENGTH attack

### ISSUE THREAD

**Issue by scottcwilson** [gburton/CE-Phoenix#778]
I have seen this done successfully against Zen Cart, and osCommerce is also vulnerable to it.  I'd be happy to submit a PR.

You can read about the attack here:
https://www.thatsoftwareguy.com/blog/2019/06/24/payment-page-credential-stealing-in-zen-cart/

**Comment by gburton** [comment]
We're moving away from the old fashioned "show message after submit if something is not right" to proper HTML5 validations.   With that in mind, is what you're thinking is needed...needed?

**Comment by BrockleyJohn** [comment]
Yes, the vulnerability is in the javascript validation code in the psigate module.

Actually it's not a vulnerability, it's a trap that can be placed to gather cc info once they've already got in.

**Comment by BrockleyJohn** [comment]
Mind you, anyone that chooses to process card info locally instead of handing  it off to the payment processor wants their head examining

**Comment by scottcwilson** [comment]
> Yes, the vulnerability is in the javascript validation code in the psigate module.

Correct - and any other contributed module with similar logic. 

Ugh bad guys. :(

**Comment by BrockleyJohn** [comment]
There's nothing you can do about addons under the current system - I expect half of them are full of vulernabilities. 

@gburton are you suggesting a rewrite of all the simple module validations from javascript to html 5 fields?

**Comment by gburton** [comment]
> @gburton are you suggesting a rewrite of all the simple module validations from javascript to html 5 fields?

Yes.

**Comment by gburton** [comment]
Are you saying that the "bad guy" is injecting a script into the DB configuration value of CC_NUMBER_MIN_LENGTH  ??   

Am I missing something?  Most likely.

**Comment by scottcwilson** [comment]
That is correct.  If you look at the article I linked, you'll see an example.

**Comment by gburton** [comment]
How is that done exactly?  What is stopping the bad guy from doing it to any DB entry.

**Comment by scottcwilson** [comment]
This field is echo'ed on the payment page, so it's able to access CC data. 
I'm just telling you what I have seen in the wild.

**Comment by gburton** [comment]
How is the DB updated to the "bad script"?  That's the question.

That is what needs to be stopped.

**Comment by scottcwilson** [comment]
A vulnerability on the hoster side. Outside the realm of osC.

**Comment by gburton** [comment]
Got it.  Name and shame the hosters and experts get to earn some bucks by fixing hacked shops.

**Comment by BrockleyJohn** [comment]
Have given some thought to moving module validation to html5 but can't see a way to mandate fields with static html - since it depends on the choice of module.
Best I could come up with for this is a class on the fields set in the modules and a change function on the module selection that clears / sets which are required, and also one to cater for the default on page display.
