### ISSUE TITLE
Test 1.0.2.0 in a number of browsers/devices

### ISSUE THREAD

**Issue by gburton** [gburton/CE-Phoenix#779]
I believe it's quite well tested, but if anyone has a spare 15 minutes to either;

download the 1.0.2.0 tree, install and have a play
-or-
have a look around the 1.0.2.0 demo and point out any issues with product display

that would be great.  Thx

**Comment by gburton** [comment]
1.0.2.0 d/load:
https://github.com/gburton/CE-Phoenix/archive/1.0.2.0.zip

1.0.2.0 demo:
https://template.me.uk/phoenix/index.php

**Comment by flyerart2B** [comment]
Hi,I did upload it to 2 tests sites (one php 7.2 - MySQL 5.7, the other php 7.3 - MYSQL 5.7) and all looks good on both, no warnings in the error logs. 
The sorting options in the product listing are great! Presentation on android devices and even Kindle good.
Do you need a translation for a French Language Pack or should I wait for further developpement?
Barbie
    Le lundi 12 août 2019 à 23:14:47 UTC+2, gburton <notifications@github.com> a écrit :  
 
 
I believe it's quite well tested, but if anyone has a spare 15 minutes to either;

download the 1.0.2.0 tree, install and have a play
-or-
have a look around the 1.0.2.0 demo and point out any issues with product display

that would be great. Thx

**Comment by gburton** [comment]
Barbie - merci pour votre temps. Attendez la version 1.0.2.0 pour faire la traduction, s'il vous plait.

**Comment by BrockleyJohn** [comment]
Tried a bunch of real mobile devices and the more modern ones seem fine.

My go-to legacy, safari on ipad 2, is still a little weird in portrait but usable and no worse than any of the previous bs4 versions.

On the bs3 template the screen width was narrow enough to push out the side columns but on bs4 they remain though too narrow for the text - see attached

![IMG_0002](https://user-images.githubusercontent.com/1625498/62938079-2d23b580-bdc6-11e9-9eea-18265edd28d9.PNG)

**Comment by flyerart2B** [comment]
Oops… Just realized that when there is only 1 product in a category like "Tomatoes" the image on the index page takes up the whole screen on my laptop, whereas in te earlier version it did not. Have not modified anything on the upload yet. See screen shot.
Barbie
    Le mardi 13 août 2019 à 13:00:06 UTC+2, gburton <notifications@github.com> a écrit :  
 
 
Barbie - merci pour votre temps. Attendez la version 1.0.2.0 pour faire la traduction, s'il vous plait.

**Comment by flyerart2B** [comment]
Hi John,My devices Samsung Galaxy 10, Samsung GalaxyTabS3 are recent, the Kindle Fire is almost 7 years old and if held in landscape position the right and left columns show properly. For mine it is just in portrait position that they bunch up on all devices. Don't know if this can help any.
Barbie
    Le mardi 13 août 2019 à 13:32:19 UTC+2, John Ferguson <notifications@github.com> a écrit :  
 
 
Tried a bunch of real mobile devices and the more modern ones seem fine.

My go-to legacy, safari on ipad 2, is still a little weird in portrait but usable and no worse than any of the previous bs4 versions.

On the bs3 template the screen width was narrow enough to push out the side columns but on bs4 they remain though too narrow for the text - see attached

**Comment by gburton** [comment]
I am pretty certain that the problem with "thin columns" presents itself in all Phoenix versions, so it's something that needs solving but is (I think!) not a bug caused by the new features in 1.0.2.0

Please confirm?

**Comment by BrockleyJohn** [comment]
@gburton yes, that's right, I think it does it on all the CE bs4 versions (just thought I'd mention now it since you're asking anyway!)

**Comment by flyerart2B** [comment]
Hello again,

Is there any reason why in a single item category like "Tomatoes" on a fresh install from the link given mine show a giant tomato that fills the whole container whereas on your demo site that does not happen? If I add 2 products the same produces, the two taking up the entire screen… until 4 products are added. This did not occur on 1.0.1.4.

Is there something different on your demo site than in the download package link ?

Thanks !
Barbie

Afficher le message d’origine

    Le mardi 13 août 2019 à 13:00:06 UTC+2, gburton <notifications@github.com> a écrit :  
 
 
Barbie - merci pour votre temps. Attendez la version 1.0.2.0 pour faire la traduction, s'il vous plait.

**Comment by gburton** [comment]
> Is there something different on your demo site than in the download package link ?

Yes, there is something different in my Demo.  Don't worry about that.

**Comment by flyerart2B** [comment]
No, uploaded directly to :www.artful-webdesign.com
php 7.38, mysql 5.7
From the link in your initial email.
    Le mercredi 14 août 2019 à 14:51:14 UTC+2, gburton <notifications@github.com> a écrit :  
 
 

Is there something different on your demo site than in the download package link ?


Yes, there is something different in my Demo. Don't worry about that.

**Comment by flyerart2B** [comment]
Seems like something from 1.0.14 concerning laege viewports changed as it is fine on devices but not pc and laptop.... it is a beautiful tomato but huge!
    Le mercredi 14 août 2019 à 14:51:14 UTC+2, gburton <notifications@github.com> a écrit :  
 
 

Is there something different on your demo site than in the download package link ?


Yes, there is something different in my Demo. Don't worry about that.

**Comment by gburton** [comment]
There is something different in my Demo.  Please stop talking about big tomatoes ;)

**Comment by flyerart2B** [comment]
Sorry... is there a way to fix this?
    Le mercredi 14 août 2019 à 15:40:57 UTC+2, gburton <notifications@github.com> a écrit :  
 
 
There is something different in my Demo. Please stop talking about big tomatoes ;)

**Comment by gburton** [comment]
Yes, and it will be available for those who are supporting the Project.  PATIENCE.

**Comment by flyerart2B** [comment]
Thank you... I am supporting the project and already donated as I do appreciate all your efforts! Hope more will.
Have a good day...Barbie
    Le mercredi 14 août 2019 à 16:02:46 UTC+2, gburton <notifications@github.com> a écrit :  
 
 
Yes, and it will be available for those who are supporting the Project. PATIENCE.
