### ISSUE TITLE
difference in configure.php files from 2.3.4 to Phoenix Edition v1.0.1.0

### ISSUE THREAD

**Issue by bitit-it** [gburton/CE-Phoenix#780]
Phoenix Edition v1.0.1.0
in admin/includes/configure.php 
isn't present:
  define('DIR_WS_IMAGES', 'images/'); 
  define('DIR_WS_ICONS', DIR_WS_IMAGES . 'icons/'); 
  define('DIR_WS_INCLUDES', 'includes/');
  define('DIR_WS_BOXES', DIR_WS_INCLUDES . 'boxes/');
  define('DIR_WS_FUNCTIONS', DIR_WS_INCLUDES . 'functions/');
  define('DIR_WS_CLASSES', DIR_WS_INCLUDES . 'classes/');
  define('DIR_WS_MODULES', DIR_WS_INCLUDES . 'modules/');
  define('DIR_WS_LANGUAGES', DIR_WS_INCLUDES . 'languages/');
  define('DIR_FS_CATALOG_IMAGES', DIR_FS_CATALOG . 'images/');

in includes/configure.php 
isn't present:
 - define('DIR_WS_IMAGES', 'images/');
-  define('DIR_WS_ICONS', DIR_WS_IMAGES . 'icons/');
  -define('DIR_WS_INCLUDES', 'includes/');
 - define('DIR_WS_BOXES', DIR_WS_INCLUDES . 'boxes/');
 - define('DIR_WS_FUNCTIONS', DIR_WS_INCLUDES . 'functions/');
 - define('DIR_WS_CLASSES', DIR_WS_INCLUDES . 'classes/');
 - define('DIR_WS_MODULES', DIR_WS_INCLUDES . 'modules/');
-  define('DIR_WS_LANGUAGES', DIR_WS_INCLUDES . 'languages/');
 - define('DIR_WS_DOWNLOAD_PUBLIC', 'pub/');

Why?  secure fix ? or bug?
Because for installing some add i had must edith the path in some file

Enrico

**Comment by gburton** [comment]
Because Phoenix is different.

**Comment by bitit-it** [comment]
Ok, maybe the question is wrong .
For installing the addon , i need of paths indicated.
can it  cause a security  problem ?

**Comment by gburton** [comment]
Don't install old addons.  Why would you?

**Comment by bitit-it** [comment]
for example for:
# html mail and newsletters 
# coupon discount 
# google shoopping feeds 
# version checker 
whats secure works addon?

**Comment by gburton** [comment]
forums.oscommerce.com for general questions, thanks.
