### ISSUE TITLE
Admin Menu Logic

### ISSUE THREAD

**Issue by Tangol** [gburton/CE-Phoenix#785]
Please note that the **Admin Menu** is very confusing for a new user.
The logical button order should be:

- Catalog
- Orders
- Customers
- Reports
- Localization
- Locations/Taxes
- PayPal
- Modules
- Tools
- Configuration

Tested on https://github.com/gburton/CE-Phoenix/commit/cc15d7670381fa6f2f6c2224f89b12bda1002136

**Comment by gburton** [comment]
Thanks for feedback.
