### ISSUE TITLE
Dependencies Update

### ISSUE THREAD

**Issue by Tangol** [gburton/CE-Phoenix#786]
Due to security and stability, some dependencies need updating **/ext/**:
- [Bootstrap-Datepicker](https://github.com/uxsolutions/bootstrap-datepicker/releases)
- [Flot](https://github.com/flot/flot/releases)
- [jQuery 2.2.4 & 3.4.1](https://github.com/jquery/jquery/releases)
- [jQuery UI 1.12.1](https://jqueryui.com/)
- [html5shiv](https://github.com/aFarkas/html5shiv/releases)
- [Respond.js](https://github.com/scottjehl/Respond/releases)
- [popper.js](https://github.com/FezVrasta/popper.js/releases)

Thanks!

**Comment by gburton** [comment]
Thanks for feedback.  At some point someone will go through these and remove any that are no longer used as well as update to latest version if used.
