### ISSUE TITLE
Code Reviews & Analytics

### ISSUE THREAD

**Issue by Tangol** [gburton/CE-Phoenix#787]
The project, doesn't use any tools for code analysis.
This is a bad thing, as sometimes bugs and vulnerabilities that are hard to spot, sneak in.

Now here's [CODACY](https://www.codacy.com/), which is free to use for open source projects.
It's an invaluable tool for checking the code quality, that should be added to the project asap.

Also, I've noticed that it's used by many high-profile CMS's.

Thanks!

**Comment by gburton** [comment]
Thanks for feedback.
