### ISSUE TITLE
data-product-price in modules

### ISSUE THREAD

**Issue by raiwa** [gburton/CE-Phoenix#788]
In the new products box, "final_price" (discounted price if is-special) is used for "data-product-price".
In the new products index and index nested module "products_price" is used (undiscounted price if is-special).
I suppose it should be "final_price"  everywhere.

**Comment by raiwa** [comment]
same in product info also purchased module, "products_price" is used

**Comment by gburton** [comment]
1.0.2.1

TY @raiwa
