### ISSUE TITLE
Dutch language files for osCom-CE-Phoenix-1.0.2.0

### ISSUE THREAD

**Issue by Denkster** [gburton/CE-Phoenix#789]
Hi,
For the better future of Phoenix, here is one contribution from me:

https://github.com/Denkster/osCom-CE-Phoenix-1.0.2.0_Dutch_language_only

This is the first time I use Github, so please contact me if I made mistakes...
Eveline

**Comment by gburton** [comment]
There seems to be no files uploaded...

Here is how the ES branch looks;  
https://github.com/raiwa/OSCOM-CE-Phoenix-Spanish-language-idioma-espanol

**Comment by Denkster** [comment]
Sorry for my learning curve.. 
I made a new repository: https://github.com/Denkster/OSCOM-CE-Phoenix_Dutch_language_Nederlandse_taal
I hope uploading the files has succeeded ?
Eveline

**Comment by gburton** [comment]
1.0.2.2
