### ISSUE TITLE
bug in html_output.php

### ISSUE THREAD

**Issue by bitit-it** [gburton/CE-Phoenix#791]
on line 70 admin/includes/functions/html_output.php
   if (ENABLE_SSL_CATALOG == 'true') {  // ERROR DON'T WORK
     	if (ENABLE_SSL == 'true') {               // WORK

Enrico

**Comment by gburton** [comment]
if (ENABLE_SSL_CATALOG == 'true') {
is correct.

**Comment by bitit-it** [comment]
ok, maybe i have found my error.
sorry

**Comment by bitit-it** [comment]
however , i keep to have this 
![oscommerce_093807](https://user-images.githubusercontent.com/43685677/63920512-5b012f00-ca41-11e9-83ee-a925015b24e2.jpeg)

**Comment by gburton** [comment]
http://forums.oscommerce.com for general questions about osCommerce.
