### ISSUE TITLE
V align label and radios in gender form

### ISSUE THREAD

**Issue by raiwa** [gburton/CE-Phoenix#794]
To vertical align label and radios in all gender forms "align-items-center" class should be added.
Example create account.php line 287:
` <div class="form-group row align-items-center">
    <label class="col-form-label col-sm-3 text-left text-sm-right"><?php echo ENTRY_GENDER; ?></label>
    <div class="col-sm-9">
`

**Comment by gburton** [comment]
Push to 1.0.2.3 branch - TY

**Comment by gburton** [comment]
1.0.2.3
