### ISSUE TITLE
product_listing - microdata missing?

### ISSUE THREAD

**Issue by cupidare** [gburton/CE-Phoenix#799]
I notice that I have more microdata in product_listing (phoenix 1.0.1.4) than in the current version: 
now: only the breadcrumb info is detected
former: there was also information for each of the shown products: i.e. breadcrumb + itemlist (one error due to a missing position info)

is this intended?

**Comment by gburton** [comment]
> is this intended?

Yes.  Project was to revamp to a better look and simplify the code.
