### ISSUE TITLE
No category Images on product pages in catalog

### ISSUE THREAD

**Issue by peterpil19** [gburton/CE-Phoenix#808]
**Explain the details for making this change. What existing problem does the pull request solve?** 

Previous versions of osCommerce (including responsive osCommerce) showed the category images in index pages. CE Phoenix does not.

This functionality has been requested. There has been some discussion on this in the Phoenix Club (steering group for Phoenix) and a suggestion a module could be created and added into core:
https://forums.oscommerce.com/topic/493874-phoenix-display-category-image-on-category-page/

The existing index products title module can easily be converted into a module which shows the category image - it was actually set up with the right code already, just nothing in the templates file calling the image.

**Test plan (required):**
Such as module has been tested already in my test shop.  It is based on the existing title module, so low risk.

_Screenshots from my test shop:_
<img width="814" alt="Screen Shot 2019-09-27 at 9 42 32 pm" src="https://user-images.githubusercontent.com/55443201/65768312-d1439f00-e16f-11e9-8aab-db86e3984631.png">
<img width="854" alt="Screen Shot 2019-09-27 at 9 42 06 pm" src="https://user-images.githubusercontent.com/55443201/65768316-d3a5f900-e16f-11e9-9f88-268a778ac29b.png">

**Comment by gburton** [comment]
TY.  osCommerce has never shown category images, from the 2.3 series onwards.  I see no reason to change that, but this can easily be an "addon"; apps.oscommerce.com
