### ISSUE TITLE
header.php - minor tidy-up - col-12 instead of col-xs-12

### ISSUE THREAD

**Issue by peterpil19** [gburton/CE-Phoenix#809]
Includes / header.php references col-xs-12 (at lines 24 and 36) for the divs containing alerts. 
Bootstrap 4 no longer requires xs as it is mobile-first. col-xs-12 can be replaced with col-12.

see: https://getbootstrap.com/docs/4.0/migration/

**Comment by gburton** [comment]
TY.  There are other areas that need attention and funnily enough this is something I worked on the other day when I had a spare 30 minutes, it is already pushed to 1.0.2.6.  

1.0.2.6
