### ISSUE TITLE
Simple version check in install.php file

### ISSUE THREAD

**Issue by peterpil19** [gburton/CE-Phoenix#811]
Apologies in advance if this suggestion is unwelcome and/or if you have considered already.

To reduce chances of people installing earlier versions of Phoenix inadvertently (which I am seeing happening to a degree), could a version check be added to the index.php install file? (In attempting to get some topics pinned in general support forum,  which I have learned is not possible, @bonbec made this suggestion to me and it made sense and thought I would pass on).

There is a version checker already in admin directory. But if too much work, even something as simple as in an an alert box which grabs the version number from version.php in github (using echo file_get_contents of the raw file /page (have tested, works) and asks the user to confirm it matches the install version prior to pressing install. The alert box could contain a link to the Github master repository and a 1 line note how to download if they need to (i.e. click 'clone or download').

**Comment by gburton** [comment]
Point releases will not be public anymore.
So the "version checker" will takae care of it.
