### ISSUE TITLE
Options & Attributes Content Module - Fails to add product to shopping cart

### ISSUE THREAD

**Issue by toneusb** [gburton/CE-Phoenix#813]
In the Options & Attributes Content Module if Enforce Selection is set to False, and Add helper text is set to True, if no option is selected, then the product will not be added to your cart.

The reason for this is twofold, firstly, because an array is passed with a non-valid ID, and secondly because OSC default doesn't allow a product that has attributes associated with it to be submitted with no attributes selected. 

My solution was to give the form an ID we can search for:

in includes/modules/content/product_info/cm_pi_options_attributes.php changed:

```
/* toneus: Change 'id' => '', to 'id' => 'NaN' */		  
          if (MODULE_CONTENT_PI_OA_HELPER == 'True') {
            $products_options_array[] = array('id' => 'NaN', 'text' => MODULE_CONTENT_PI_OA_ENFORCE_SELECTION);            
          }
```

Then look for 'NaN' and remove it from the array. Pass the rest of the array if valid, but if not then just remove the array altogether:

In includes/actions/add_product.php just after

`$attributes = isset($_POST['id']) ? $_POST['id'] : '';
`
Add:

```
/* toneus */
		if( is_array( $attributes ) ) {
			foreach( $attributes as $k=>$v ) {
				if( $v == 'NaN' ) {
					// Do nothing 
				} else {
					$check[$k] = $v;
				}
			}
			$attributes = $check;
		}
/* end */

```
The next problem is that OSCommerce will check to see if the product should have attributes and will block adding to the cart if true. So we need to remove this check in the class:

In includes/classes/shopping_cart.php

change

```
      } elseif (tep_has_product_attributes($products_id)) {
		$attributes_pass_check = false;
		}
```

to
```
      } elseif (tep_has_product_attributes($products_id)) {  
		if (MODULE_CONTENT_PI_OA_ENFORCE == 'True') $attributes_pass_check = false;
		}
```

**Comment by gburton** [comment]
TY, but...this seems like a lot of kludge code for no good reason => just enforce a selection.

Or...create a new module if the core one doesn't quite float your boat.

**Comment by toneusb** [comment]
The issue was you may not want to enforce a selection. For example if you wanted to offer optional extras with a product. In which case setting Enforce Selection to False and having Helper Text on seems a great solution for this. The way it is however, the Enforce Selection option isn't in fact an option at all. If you set it to False, a user would expect not to have to select an option, but if you don't select one, then adding to cart doesn't work. IMO I think the best solution would be to remove this option entirely - then the system would work as default OSC does.  The problem with a new module is that the shopping_cart class also needs to be changed, so a new module would become complex....
