### ISSUE TITLE
Boxes on Specific Pages

### ISSUE THREAD

**Issue by LeeFoster** [gburton/CE-Phoenix#815]
As part of a website I built for myself I made some changes to allow the owner to choose what boxes appear on which pages.

This involves adding the get pages function to the general.php file in both Admin and Shop and then adding the code from the date picker header tag module to the bm_*.php files.

**Comment by gburton** [comment]
Does the average shopowner need that?

**Comment by LeeFoster** [comment]
Not sure, worth putting to the forum?

**Comment by gburton** [comment]
I don't really want to add more stuff...it just means more code to have to support and answer questions about.

**Comment by LeeFoster** [comment]
As a module then, so people can have it if they want?

**Comment by BrockleyJohn** [comment]
Can be an addon with no core changes
