### ISSUE TITLE
search_in_descriptions

### ISSUE THREAD

**Issue by peterpil19** [gburton/CE-Phoenix#816]
Hi,

Searching in descriptions is not available in cm_header_search.php (no code to toggle it on) and disabled in bm_search.php (with 'search_in_descriptions' set to 1 in the code).

This could potentially lead to some confusion amongst shop owners who are not aware of this as indeed I was not myself until searching my catalogue earlier today.

It is a very simple code change to make searching in descriptions selectable from admin. That would also help resolve the inconsistency between the two modules (where one has the code to toggle and the other doesn't) and assist shop owners in being aware of this search behaviour in case it is relevant to their customers.

**See the following files as an example - tested in my test shop:**

[bm_search.txt](https://github.com/gburton/CE-Phoenix/files/3721454/bm_search.txt)
[cm_header_search.txt](https://github.com/gburton/CE-Phoenix/files/3721455/cm_header_search.txt)

Peter

**Comment by gburton** [comment]
The only place where "search in description" should be available is at the actual advanced_search.php page.  The other searches are for "quick search".
