### ISSUE TITLE
hardcoded screenreader text in split page results

### ISSUE THREAD

**Issue by raiwa** [gburton/CE-Phoenix#817]
There is a hardcoded screenreader text left over since  OsC 2.3.x in includes/classes/split_page_results.php
line 107:
`<span class="sr-only">(current)</span>`
should be:
`<span class="sr-only">' . sprintf(PREVNEXT_TITLE_PAGE_NO, $jump_to_page) . '</span >`

**Comment by gburton** [comment]
This can be changed at some point in the future, dependant on more shop-owners and more developers getting more involved in supporting the project.
