### ISSUE TITLE
Add preplaced hook calls to other form pages

### ISSUE THREAD

**Issue by raiwa** [gburton/CE-Phoenix#818]
It would be useful to add the preplaced hook calls "injectFormVerify" and "injectFormDisplay" also to the following files:
- account_edit.php
- address_book_process.php + address_book_details.php
- checkout_shipping_address.php + checkout_new_address.php
- checkout_payment_address.php (+ checkout_new_address.php)

**Comment by gburton** [comment]
Maybe at some point in the future, dependant on more shop-owners and more developers getting more involved in supporting the project.

**Comment by ecartz** [comment]
@gburton  If you want, you can assign this to me.  I suspect that it will be trivial to do with my other changes.

**Comment by gburton** [comment]
1.0.3.0 (for checkout pages)

**Comment by ecartz** [comment]
https://github.com/gburton/CE-Phoenix/commit/30de20c97dd41bb024855140e3dea0d4a7ee796e

1.0.5.3

I think that I may have regressed this in 1.0.5.1
