### ISSUE TITLE
Navigation History

### ISSUE THREAD

**Issue by BrockleyJohn** [gburton/CE-Phoenix#819]
Maybe I'm confusing bespoke implementations with core functionality, but if I navigate from home to fruit and add a box of 24 apples to the cart, the navigation history is set to:

`
Array
(

    [0] => Array
        (
            [page] => index.php
            [mode] => NONSSL
            [get] => Array
                (
                )
            [post] => Array
                (
                )
        )
    [1] => Array
        (
            [page] => product_info.php
            [mode] => NONSSL
            [get] => Array
                (
                    [cPath] => 1
                    [products_id] => 4
                    [action] => add_product
                )
            [post] => Array
                (
                    [id] => Array
                        (
                            [1] => 2
                        )
                    [products_id] => 4
                )
        )
    [2] => Array
        (
            [page] => shopping_cart.php
            [mode] => NONSSL
            [get] => Array
                (
                )
            [post] => Array
                (
                )
        )
)
`
I was expecting the entry before the product to be the category not the home page (ie it's missing the cPath for fruit)

Waddayafink?

**Comment by gburton** [comment]
I think so.  Have a look in to it?

**Comment by BrockleyJohn** [comment]
Hmm, today it's behaving as expected (same code, same site). I guess I must have clicked on the apples in new products instead of going into fruit as I believed - that would make the history valid.

Can't see any other explanation at this point. Will re-open if I find some other way of getting the same result.
