### ISSUE TITLE
Finish Tell a Friend deprecation

### ISSUE THREAD

**Issue by ecartz** [gburton/CE-Phoenix#820]
The changes that I'm making to the customer account information will break the current version of the Tell a Friend page.  Since that page is deprecated (as discussed in the [Phoenix club](https://forums.oscommerce.com/topic/494101-tell-a-friend-potential-removal-of/)), I would prefer not to modify it.  Rather than leave a broken page in the install, I propose to delete the page and the references to it.  That way no one will expect to be able to reenable the page.  

My proposed changes are visible at https://github.com/gburton/CE-Phoenix/compare/master...ecartz:deprecate-tell-a-friend

I delete three files and the references to those files in two other files.

**Comment by gburton** [comment]
TY @ecartz - this was already done in 1.0.2.6
