### ISSUE TITLE
Undefined $cInfo in admin/orders.php

### ISSUE THREAD

**Issue by ecartz** [gburton/CE-Phoenix#821]
Currently in admin/orders.php at line [499](https://github.com/gburton/CE-Phoenix/blob/3c1e4e4adf7460506184e2e5c2ec1820aa0b66d4/admin/orders.php#L499) there is 

`      $contents[] = array('text' => TEXT_INFO_DELETE_INTRO . '<br /><br /><strong>' . $cInfo->customers_firstname . ' ' . $cInfo->customers_lastname . '</strong>');`

But `$cInfo` does not seem to be defined in that file.  It has `$oInfo`.  So I think that this should be 

`      $contents[] = array('text' => TEXT_INFO_DELETE_INTRO . '<br /><br /><strong>' . $oInfo->customers_name . '</strong>');`

**Comment by BrockleyJohn** [comment]
That shows how little Delete Order is used!

**Comment by ecartz** [comment]
That was one of my first thoughts too.  Since this was original code and nothing about `$cInfo` seems to have changed since then.

**Comment by gburton** [comment]
1.0.2.8
