### ISSUE TITLE
Customer's name

### ISSUE THREAD

**Issue by ecartz** [gburton/CE-Phoenix#822]
I found two examples of files that were manually assembling the customer's name from the first and last name without using other customer fields.  Since I would like to give the store owner more options about creating the customer name, I want to centralize this logic.  So rather than go through every file using the customer name for each change, I can just change that once.  

Proposal:  https://github.com/gburton/CE-Phoenix/compare/master...ecartz:customers_name?expand=1

This change makes it so that these files are outside my project scope.  I can make this simple change now and the files will work both before and after my other changes without touching them again.

**Comment by gburton** [comment]
Go ahead, but don't change the paypal app at all pls - we're waiting on an update for that from HPDL.
Everything else - feel free to change.  Send me a PR once complete?

**Comment by ecartz** [comment]
> don't change the paypal app at all pls

So I guess I can't just install [Checkout Redux](https://apps.oscommerce.com/ZqbsQ&checkout-redux) into core then.  😭  Because [this comment](https://github.com/gburton/CE-Phoenix/pull/832#issuecomment-554765166), [this one](https://forums.oscommerce.com/topic/398887-paypal-app-for-oscommerce-online-merchant/?do=findComment&comment=1798602), and the two hundred lines of code that I just edited in rbsworldpay_hosted.php have me really missing it.  Especially when I think about all the other payment modules that have the exact same code in them for at least half of that.

**Comment by ecartz** [comment]
Well, we could remove the contents of [this (Javascript) function](https://github.com/gburton/CE-Phoenix/blob/ef265330ef228fd71d59cb302a3a4874dede823b/admin/paypal.php#L387):  

```
      versionCheckNotify: function() {
        if ( (typeof this.versionCheckResult[0] != 'undefined') && (typeof this.versionCheckResult[1] != 'undefined') ) {
          if ( this.versionCheckResult[1] > this.version ) {
            $('#ppAppUpdateNotice').show();
          }
        }
      }
```

I haven't looked at it enough to tell if we'd also need to do something at application start.

**Comment by osc2nuke** [comment]
> The paypal app is updateable from within admin, so if you make changes to that...and then shopowner updates it, your changes are gone. Any way around that ?

Yep................ a
customer.php CLASS 
( at least it is a start for H , give him the static info given by the system )
That customer.php class can be huge and even is able to handle customer groups.
Discounts/Vouchers and other shop "restrictions".

But that is my 5$ cents

**Comment by gburton** [comment]
@osc2nuke, you've sidestepped the question I think.  If a customer class is added in Phoenix...and the  phoenix paypal app is updated to use it...and then a shopowner in the future updates the oscommerce paypal app from admin...the changes made to the phoenix paypal app are lost.   A customer class is not the answer in this situation...I believe. 

@ecartz, taking out the ability to update the paypal app from admin maybe the answer.

**Comment by osc2nuke** [comment]
@gburton 
Yes you right, i missed it.

**Comment by ecartz** [comment]
So I've pushed my changes into public source control:  https://github.com/ecartz/CE-Phoenix/tree/1.0.4.4

That's basically the 1.0.4.4 release with my changes added.  I'm still targeting them for a 1.0.5.1 release, as should be visible in the system/versioned directory.  

I'm still working on testing, so certainly don't use it for a live store.  But it's available if you want to play around with the new features.

**Comment by ecartz** [comment]
Now included in the current development branch at https://github.com/gburton/CE-Phoenix/tree/1.0.5.1
