### ISSUE TITLE
siteWide injectSiteStart hook in /admin/includes/template_top.php

### ISSUE THREAD

**Issue by stevang** [gburton/CE-Phoenix#826]
please add to /admin/includes/template_top.php

`<?php echo $OSCOM_Hooks->call('siteWide', 'injectSiteStart'); ?>`

for example right after:
`<base href="<?php echo ($request_type == 'SSL') ? HTTPS_SERVER . DIR_WS_HTTPS_ADMIN : HTTP_SERVER . DIR_WS_ADMIN; ?>" />`

and 
folder /www/includes/hooks/admin/siteWide/

to make an injectSiteStart hook available for the admin side (as seen on the catalog side).

Thanks!

**Comment by gburton** [comment]
Go ahead and push a PR 👍

**Comment by gburton** [comment]
1.0.3.0
