### ISSUE TITLE
Demo Site.

### ISSUE THREAD

**Issue by mallenjordan** [gburton/CE-Phoenix#833]
I don't know if I am doing something wrong but every time I try to access the Demo site it keeps loading as ERR_CONNECTION_RESET.

I am behind a VPN but the gateway should allow this to be accessed from my side.

**Comment by gburton** [comment]
Try it with VPN turned off.  Then you'll know if it is a VPN issue or not.
Let us know ?

**Comment by gburton** [comment]
No response.  Assume bogus "issue".
