### ISSUE TITLE
undefined index errors produced by admin box module redesign

### ISSUE THREAD

**Issue by raiwa** [gburton/CE-Phoenix#836]
When error reporting set to ALL, the new modularized admin boxes throw undefined index notice errors for "title", "heading" and "link" in column_left.php.
I fixed it adding empty arrays to all main modules (catalog.php, configuration.php ...)
You can pull it from here:
https://github.com/raiwa/Responsive-osCommerce/tree/modularize-admin-boxes

**Comment by gburton** [comment]
TY 1.0.4.1
