### ISSUE TITLE
glitches in testimonials content module

### ISSUE THREAD

**Issue by raiwa** [gburton/CE-Phoenix#837]
1. This condition is wrong defined:`      if (MODULE_CONTENT_TESTIMONIALS_LIST_ALL == 'All') {
`, it shoud be just opposit:
 `if (MODULE_CONTENT_TESTIMONIALS_LIST_ALL != 'All') {`
or:
if (MODULE_CONTENT_TESTIMONIALS_LIST_ALL == 'Language Specific') {

2. Unused language definition is left in main language file: `TEXT_NO_TESTIMONIALS`
3. Language definition `TEXT_DISPLAY_NUMBER_OF_TESTIMONIALS` should be moved to module

**Comment by gburton** [comment]
TY 1.0.4.1
