### ISSUE TITLE
sagepay form integration uses mcrypt

### ISSUE THREAD

**Issue by BrockleyJohn** [gburton/CE-Phoenix#838]
mcrypt was deprecated in php 7.1 and removed in 7.2

sagepay_form uses mcrypt_encrypt and mcrypt_decrypt

It needs replacing with openssl encrypt / decrypt

**Comment by BrockleyJohn** [comment]
hdpl made a version for @heatherbell

I have tested it too (and removed commented code lines for clarity) - ready for pr

**Comment by gburton** [comment]
Push to 1041 branch pls, I'll take a look.

**Comment by gburton** [comment]
1.0.4.1

TY
