### ISSUE TITLE
Payment modules field validation loads before jquery - and fields look crap

### ISSUE THREAD

**Issue by BrockleyJohn** [gburton/CE-Phoenix#843]
Payment modules that require on-site input of card data have jquery-based field validation but it is loaded into header_tags.

Affected modules: 
paypal_pro_payflow_dp
sage_pay_direct (I have tested the fix on this one)
braintree_cc
paypal_pro_dp
stripe

Currently they throw a '$ is not defined' console error on the confirmation page.

The solution is a one-word change to each resulting in the following line:
`        $GLOBALS['oscTemplate']->addBlock($this->getSubmitCardDetailsJavascript(), 'footer_scripts');
`

**Comment by BrockleyJohn** [comment]
And.. the date fields look awful - see attached
![2019-12-01 (8)](https://user-images.githubusercontent.com/1625498/69965056-58641900-150b-11ea-9ffc-26400c878b3b.png)

Adding a class to the containing td makes it easy to style them to reset the width and flow inline - though I'm unsure where best to put that:
`.date-fields .form-control {width:auto;display:inline-block}`

**Comment by BrockleyJohn** [comment]
...into header_tags within the module perhaps?

**Comment by gburton** [comment]
Push to 1.0.4.1 when ready.

**Comment by gburton** [comment]
1.0.4.1 TY
