### ISSUE TITLE
specials with no limit in ht_product_schema.php

### ISSUE THREAD

**Issue by cupidare** [gburton/CE-Phoenix#847]
If a special offer runs without limit, there is a problem in the microdata... I suggest to change line 81

`$schema_product['offers']['priceValidUntil'] = $specials_expiry['expires_date'];`

to 

`$schema_product['offers']['priceValidUntil'] = is_null($specials_expiry['expires_date']) ? date('c', strtotime("+14 day", time())) : $specials_expiry['expires_date'];`

**Comment by ecartz** [comment]
According to [the Google webmasters forum](https://support.google.com/webmasters/thread/2281024?hl=en):  

> But if you don't have an expiration date, don't be tempted to fake one just to clear a heads-up warning. Keep your data accurate, and use the field if and when it becomes appropriate, like if a product went on sale, i.e. 10% off until June 10th, you could then add the priceValidUntil for that, then remove it when it's gone back to normal.
> 
Rule of thumb with structured data is be accurate & truthful. If a particular field isn't valid for your site, don't be tempted to fudge it. Just leave it.

So we should not put in a date of two weeks unless someone has set that.  

If the solution you posted produces a value that looks correct, a better version would be 

```
if (isset($specials_expiry['expires_date']) && tep_not_null($specials_expiry['expires_date'])) {
  $schema_product['offers']['priceValidUntil'] = $specials_expiry['expires_date'];
}
```

Then it won't promise that the price will be valid for two weeks when it might change at any time.  It simply won't set the value that it does not actually know.

**Comment by BrockleyJohn** [comment]
A warning in the structured data testing tool is simply that - it only indicates a problem if you have data that is not coming out. You should not be inventing data to feed to google.

This issue is a duplicate - it's been raised before.
