### ISSUE TITLE
Autoloading classes

### ISSUE THREAD

**Issue by ecartz** [gburton/CE-Phoenix#849]
Should we implement a class [autoloader](https://www.php.net/manual/en/function.spl-autoload-register.php)?  

Currently classes are simply loaded by appearing in application_top.php or manually loaded in specific pages.  But I currently have several classes that are dependent on each other and which might have other modules/classes dependent on them.  As such, I don't really know when they'll be needed.  So I end up with a lot of boilerplate 

```
if (!class_exists('foo')) {
  include 'foo.php';
}
$foo = new foo();
```

Apparently the modern solution to this is to implement an autoloader which looks for classes in the specified locations.  For example, includes/classes or includes/modules/*

So we could just write 

```
$foo = new foo();
```

and have it implicitly do the class existence and file checks for us.  

Are we avoiding that for a reason?  Or should I just go ahead, create an autoloader, and start using it for new classes?  Then we could peel back the other instances as we go.  

Overall, this would be less code and fewer worries about order.  Because with this, use will trigger loading rather than us having to do it manually.

**Comment by BrockleyJohn** [comment]
Perhaps autoloading and namespaces should go hand in hand, it avoids conflicts and helps organise the code.

**Comment by BrockleyJohn** [comment]
incidentally, include_once('foo.php') would save a couple of lines

**Comment by gburton** [comment]
Sure thing, an autoloader is on my list of to-do but it hasn't gotten done in 3 yrs, so probably won't (by me).

**Comment by gburton** [comment]
New install of 1042 branch, gives (note I have shortened the Paths for readability);

Warning: scandir(includes/system/versioned,includes/system/versioned): The system cannot find the path specified. (code: 3) in \1.0.4.2\includes\functions\autoloader.php on line 14

**Comment by ecartz** [comment]
System/versioned is intended for those files that modules access, e.g. order.php, shopping_cart.php, shipping.php, etc.  So the "system" will use the latest version, but a module can choose to use an older version until we drop support.  This will allow us to update the API for things like order and shopping_cart while retaining backward compatibility for those things that really need it.  

A forward looking solution to the error would be to move includes/classes/shopping_cart.php to something like includes/system/versioned/1.0.0.0/shopping_cart.php and delete lines [118-120 of includes/application_top.php](https://github.com/gburton/CE-Phoenix/blob/1.0.4.2/includes/application_top.php#L119):  

```
// include shopping cart class
  require('includes/classes/shopping_cart.php');
```
Coded.

Or as you note, deleting [line 40 of includes/functions/autoloader.php](https://github.com/gburton/CE-Phoenix/blob/1.0.4.2/includes/functions/autoloader.php#L40) resolves the immediate error.

**Comment by gburton** [comment]
Got it.  Nice!

> A forward looking solution to the error would be to move includes/classes/shopping_cart.php to something like includes/system/versioned/1.0.0.0/shopping_cart.php and delete lines [118-120 of includes/application_top.php](https://github.com/gburton/CE-Phoenix/blob/1.0.4.2/includes/application_top.php#L119):

Is the way forward.
