### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by ecartz** [gburton/CE-Phoenix#850]
As we all know, there are two hard problems in computer work:  cache invalidation; naming; and off-by-one errors.  If we start adding namespaces, what should they be?  2.4 and 3.0 were going with something like OSC\OM.  Should Phoenix start with that?  Or should it be something like Phoenix\ ?

Also, what should we do about modules?  Write out something like Phoenix\Modules\Shipping or Phoenix\Modules\Content\Account ?  Or some kind of abbreviation system?    E.g. OSC\CE\M\SH and PH\CM\cm_account_title or CE\cm_account_title.  Where the PH stands for Phoenix and the CE stands for Community Edition.  We'd pick one of the options, not all five at once.  

I would slightly prefer writing them out.  We don't have to write them that often and we need to read them more frequently.  But this would be something that all developers will have to live with later.  So we should strive for some kind of consensus.  

Part of why I ask this now is that namespaces can make the autoloader work more easily.  As instead of looking in every subdirectory of includes/modules, we can go straight to modules/content/account if that has a unique namespace.  

Or maybe it's enough to parse the class name as is.  E.g. cm_account_title is in includes/modules/content/account/cm_account_title.php.  I can try that approach if people are reluctant to use more formal namespaces.

**Comment by gburton** [comment]
> I would slightly prefer writing them out.

This, I think.

**Comment by BrockleyJohn** [comment]
Short and meaningful as you have written out is better than TLAs. Totally hate the idea of parsing class names, that's just wrong!

**Comment by MOPS-DanCole** [comment]
As I get older and older readability becomes more and more important.  Don't laugh it'll happen to all of you too, if you're lucky. LOL.  I would favor writing them out.
