### ISSUE TITLE
Rename navbar_modules?

### ISSUE THREAD

**Issue by ecartz** [gburton/CE-Phoenix#851]
If we're going to namespace to something like Cart\modules\navbar_modules, then that name looks a bit redundant.  I would prefer to name more like Cart\modules\navbar but I'd like to have the property that the namespace match the directories.  

Of the twelve files that reference navbar_modules, I have to edit ten of them for templating.  In fact, my proposed edit would remove the reference to navbar_modules in those ten files.  I also would need to edit them for namespaces.  So this seems like a reasonable time to rename them from navbar_modules to just navbar to be consistent with the other module directories.

**Comment by gburton** [comment]
Sure.  Go ahead.
Unsure why I called it "navbar_modules" and not just "navbar".
