### ISSUE TITLE
Delete includes/functions/compatibility.php

### ISSUE THREAD

**Issue by ecartz** [gburton/CE-Phoenix#861]
Is there any reason not to delete everything from includes/functions/compatibility.php except the time zone configuration?  I note that that happened at [this commit](https://github.com/osCommerce/oscommerce2/commit/b5fc46d17c839609fa6e769cd74ee6ca43954890#diff-6b1cbe14fec9bfce52a4e475db58d2cb) in the osCommerce repository.  And it doesn't seem to have done anything else at the same time.  This suggests to me that we could just drop it and move the time zone configuration directly into application_top.php

What I'm looking for is some reason why it was useful.  Was there some obscure case where something broke because of it?

**Comment by gburton** [comment]
There is no reason not to nuke it.
