### ISSUE TITLE
Replacing tep_session functions with $_SESSION

### ISSUE THREAD

**Issue by ecartz** [gburton/CE-Phoenix#863]
I am currently looking at `(tep_session_is_registered('customer_id') ? $customer_id : null)` which could be just `$_SESSION['customer_id'] ?? null` and get the same effect with less code there.  And it would process less code (no function call and only load one variable from memory rather than two copies of the same value).  

The `$_SESSION` version of this is so much simpler than the original PHP handling that I can't see any reason for `tep_session_is_registered`, `tep_session_unregister`, and `tep_session_close` anymore.  So I'd like to start replacing them wherever I encounter them.  

Is there any reason not to do that?  

It also might make sense to replace `tep_session_id`, `tep_session_name`, and `tep_session_save_path` with the native PHP functions when called with no arguments.  The only time they do anything other than call the native function is if called with a potentially empty argument.  

The` tep_session_start`, `tep_session_destroy`, and `tep_session_recreate` do actual work that we should probably retain.  

I'm of two minds about` tep_session_register`. It's a little more complicated than a simple wrapper, but I'm not sure that it couldn't usually be written more simply.  The complicated cases are when the global variable doesn't exist yet or the session hasn't started.  But we usually know that when using it.  So perhaps we should start replacing it when we know we're in the simple case.

**Comment by gburton** [comment]
> Is there any reason not to do that?

There is no reason not to do that.
