### ISSUE TITLE
password_reset.php doesn't work with mail adresses containing a +

### ISSUE THREAD

**Issue by jomat** [gburton/CE-Phoenix#864]
If a user with a mail adress containing a + wants to reset their password, they receive the mail with the password reset link with the + url encoded to a %2b, and after entering a new password and confirming, it fails with:

Error: The E-Mail Address was not found in our records, please try again.

**Comment by ecartz** [comment]
A simple fix in the short term would be to strip out the plus sign before URL encoding and before comparison (from the saved copy).  

For the long term solution, I'll test that this is working when I test my other changes to that page.
