### ISSUE TITLE
Fix me 

### ISSUE THREAD

**Issue by ruden** [gburton/CE-Phoenix#866]
Notice: Undefined index: title in /admin/includes/column_left.php on line 64
https://github.com/gburton/CE-Phoenix/blob/693ea25ded39c2439d53215ee36db7b6387feefd/admin/includes/boxes/customers.php#L16
https://github.com/gburton/CE-Phoenix/commit/2e397007e1a4128c17328859ac112699fd8abf56#diff-990c8b7556662f82f2342c49fdf69335

**Comment by ecartz** [comment]
https://github.com/gburton/CE-Phoenix/commit/3db8193c1fae5be2f8a8c52eddf80f43ba5e4348#diff-990c8b7556662f82f2342c49fdf69335

**Comment by ruden** [comment]
a simple solution without using an empty array
```
  $cl_box_groups[] = array(
    'heading' => BOX_HEADING_CUSTOMERS,
    'apps' => array(
    )
  );
```
