### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by chrbronikowski** [gburton/CE-Phoenix#874]
Phoenix v1.0.4.1

Please have a look at the following code, as these might be some typos found in the code.

#######################################################
checkout_payment.php line 124 --> p_ vs d_
`                  echo tep_draw_radio_field('payment', $selection[$i]['id'], ($selection[$i]['id'] == $payment), 'id="p_' . $selection[$i]['id'] . '" required aria-required="true" aria-describedby="d_' . $quotes[$i]['methods'][$j]['id'] . '" class="custom-control-input"');`

// Correction
                  `echo tep_draw_radio_field('payment', $selection[$i]['id'], ($selection[$i]['id'] == $payment), 'id="p_' . $selection[$i]['id'] . '" required aria-required="true" aria-describedby="p_' . $selection[$i]['id'] . '" class="custom-control-input"');`
######################################################
checkout_payment.php line 197
// Possible language tag, does not follow spelling from checkout_shipping.php --> TITLE_ vs BUTTON_
` <div class="text-right"><?php echo tep_draw_button(TITLE_CONTINUE_CHECKOUT_PROCEDURE, 'fas fa-angle-right', null, 'primary', null, 'btn-success btn-lg btn-block'); ?></div>`

// Correction	
	`<div class="text-right"><?php echo tep_draw_button(BUTTON_CONTINUE_CHECKOUT_PROCEDURE, 'fas fa-angle-right', null, 'primary', null, 'btn-success btn-lg btn-block'); ?></div>`
#######################################################
checkout_payment.php line 184 --> text-left
 `<label for="inputComments" class="col-form-label col-sm-4 text-sm-right"><?php echo ENTRY_COMMENTS; ?></label>`

// Correction
    `<label for="inputComments" class="col-form-label col-sm-4 text-left text-sm-right"><?php echo ENTRY_COMMENTS; ?></label>`

**Comment by BrockleyJohn** [comment]
`aria-describedby` should refer to the id of the label, not the field (so no it shouldn't be p_)

Text alignment of comment is text-left by default, there's no need to specify it (have you tried if it works?)

**Comment by ecartz** [comment]
I agree that the language constant is inconsistent, but it does match the language file.  If we changed it, we'd have to change both.  It's not currently broken, just odd looking.

**Comment by gburton** [comment]
TY

1.0.4.2 for the describedby and the inconsistent button constant.

text-left not needed as per Johns comment above
