### ISSUE TITLE
Undefined constant warning causes paypal start fail on phoenix 1.0.4.0

### ISSUE THREAD

**Issue by BrockleyJohn** [gburton/CE-Phoenix#883]
Paypal app start on clean install; result (when display errors is true):

Warning: Use of undefined constant OSCOM_APP_PAYPAL_LOGIN_SORT_ORDER - assumed 'OSCOM_APP_PAYPAL_LOGIN_SORT_ORDER' (this will throw an Error in a future version of PHP) in [physical catalog]/includes/modules/content/login/cm_paypal_login.php on line 41

then tep_redirect fails:
Warning: Cannot modify header information - headers already sent by (output started at [physical catalog]/includes/modules/content/login/cm_paypal_login.php:41) in [physical admin]/includes/functions/general.php on line 38

Cause: when you hit start the paypal app goes through all the modules and checks if they can be migrated. Whether they can be or not, it creates a config entry for the status of each of them (and defines them for the current run):
`$this->saveParameter('OSCOM_APP_PAYPAL_' . $module . '_STATUS', '');`

This means that the installation check in the login content module doesn't work 
`      if ( defined('OSCOM_APP_PAYPAL_LOGIN_STATUS') ) {`
`        $this->sort_order = OSCOM_APP_PAYPAL_LOGIN_SORT_ORDER;`
`        $this->enabled = in_array(OSCOM_APP_PAYPAL_LOGIN_STATUS, array('1', '0'));`
`...`
as the status config is defined whether or not it's installed. Subsequently accessing admin/modules/content/install throws the same warning until/unless the module has been installed.

Minimal impact fix is to test if sort order constant is defined which eliminates all symptoms - tested on 1.0.4.3
`$this->sort_order = (defined('OSCOM_APP_PAYPAL_LOGIN_SORT_ORDER') ? OSCOM_APP_PAYPAL_LOGIN_SORT_ORDER : 0);`

**Comment by gburton** [comment]
Please push fix to 1.0.4.3 branch.  TY.
