### ISSUE TITLE
Uncaught Error: Call to a member function getData() on null

### ISSUE THREAD

**Issue by chrbronikowski** [gburton/CE-Phoenix#886]
I believe these errors to be a global issue, related to the change: "Plug manufacturers class into the Schema output."  but I would also like to provide some background information just in-case this is a single user issue related to custom modifications.  I started with a clean install of Phoenix v1.0.1.0.  The site currently has several custom advanced modifications, but I have been following the Commits, and have manually been updating the changes to reflect v1.0.4.2.  However, after making changes, sometime after v1.0.4.0, which was current at the time, I started to randomly receive these errors below that I was not able to replicate on my own, and not sure how it was triggering obtain a 'null' value thus trigger the error.  If i disabled the module 'ht_manufacturer_title' it would seem the error goes away.  Also, there are no modification to class/manufacturer.php or ht_manufacturer_title.php file, they were copied directly from the latest version v1.0.4.2 Based on the information below, could you tell me what is triggering this error, so I can try to manually replicate it, to better understand the cause. Thank you

> PHP Fatal error:  Uncaught Error: Call to a member function getData() on null in /public_html/includes/modules/content/index_products/cm_ip_title.php:45
Stack trace:
#0 /public_html/includes/classes/osc_template.php(147): cm_ip_title->execute()
#1 /public_html/index.php(57): oscTemplate->getContent('index_products')
#2 {main}
  thrown in /public_html/includes/modules/content/index_products/cm_ip_title.php on line 45

> PHP Fatal error:  Uncaught Error: Call to a member function getData() on null in /public_html/includes/modules/header_tags/ht_manufacturer_title.php:36
Stack trace:
#0 /public_html/includes/classes/osc_template.php(102): ht_manufacturer_title->execute()
#1 /public_html/includes/template_top.php(13): oscTemplate->buildBlocks()
#2 /public_html/index.php(35): require('/home/...')
#3 {main}
  thrown in /public_html/includes/modules/header_tags/ht_manufacturer_title.php on line 36

>   Plug manufacturers class into the Schema output.
  https://github.com/gburton/CE-Phoenix/commit/604bb9bc64c4eb23449e90610b7aa79840f11653#diff-b2da8d88a9181dbed61d853d10f348ef

>

**Comment by ecartz** [comment]
Try changing [line 44 of includes/modules/content/index_products/cm_ip_title.php](https://github.com/gburton/CE-Phoenix/blob/684951f08a5ed4d020b8a137a3850069c057ee41/includes/modules/content/index_products/cm_ip_title.php#L44) from 

```
      if (isset($_GET['manufacturers_id']) && !empty($_GET['manufacturers_id'])) {
```

to 

```
      if (isset($brand) && ($brand instanceof manufacturer)) {
```

And [line 35 of includes/modules/header_tags/ht_manufacturer_title.php](https://github.com/gburton/CE-Phoenix/blob/684951f08a5ed4d020b8a137a3850069c057ee41/includes/modules/header_tags/ht_manufacturer_title.php#L35) from 

```
        if (isset($_GET['manufacturers_id']) && is_numeric($_GET['manufacturers_id'])) {
```
to 
```
        if (isset($brand) && ($brand instanceof manufacturer)) {
```

That should get around the immediate problem.  

For sources, I would check if you might have junk data in the manufacturers table.  What it is saying is that manufacturers_id is set in the URL but the manufacturers class is not getting created.  This will happen if the URL also has a cPath.  E.g. https://template.me.uk/phoenix/index.php?cPath=1&manufacturers_id=1 causes a white screen on the demo site.

**Comment by chrbronikowski** [comment]
Thank you for the response.  I was able to manually replicate the error by calling 'manufacturers_id=' on the index.php page.  If I understand correctly, the parameter 'manufacturers_id' probably exists in a custom link, and is referencing the 'index.php' page, when the correct parameter 'filter_id' should be used to retrieve the manufacturer products on the 'index.php' page.

**Comment by ecartz** [comment]
>  If I understand correctly, the parameter 'manufacturers_id' probably exists in a custom link, and is referencing the 'index.php' page, when the correct parameter 'filter_id' should be used to retrieve the manufacturer products on the 'index.php' page.

Yes, that is one possibility.  Note that if it only says, manufacturers_id, that's fine.  But if there is a cPath set, it is supposed to be filter_id instead.  And no, I don't know why that is so.  I just looked at the code and the behavior and observed it.  

Obviously I can't say that is what is happening on your site.  But it would fit the behavior that you describe.

**Comment by gburton** [comment]
What was the problem and what is/was the fix?
Does this need attention in the core code, or was it single user issue?

**Comment by chrbronikowski** [comment]
The solution provided by ecartz seems to have eliminated the errors.  Based on the understanding of the issue and being able to manually replicate it, I would think this is an isolated issue related to customization of using multiple filter options on the website.  I currently, have not found the links in the code that were actually triggering the error.  It was just strange, ever since upgrading several, multiple high traffic website since early 2019 that this error was never seen, until  applying Phoenix changes related to the version updates.  What made the issue more weird is that it only triggered the error 2-5 times per day on a site receiving 20K unique page views.  So, i'm not sure if there is a broken link on the web somewhere, or if someone is using known parameters to try and extract web content, trigger the error.  I will continue to monitor and look for the original cause of the issue, and post an update if I find anything new.

**Comment by ecartz** [comment]
In my testing, the cm_ip_title.php change could still generate an error.  Because it doesn't check if the category is set before attempting to use it.  So I deleted the branch where I made that change.  

It's not clear to me if it is better to not generate an error if the URL is malformed.  I would guess that content is at least slightly broken here when this happens.  But if we make my proposed change, the content might be silently broken.  In fact, that's what my testing showed.  That's why I haven't requested pull for the replacement branch, even though I did code it.  

Broken URL:  https://template.me.uk/phoenix/index.php?cPath=1&manufacturers_id=1

But even with this fix, that URL still shows the "wrong" content, not filtering by manufacturers_id as seems to be intended.  I do not see a way to generate that URL by clicking.  I composed it manually.  

I'm wondering if the long term solution might not be to revisit how filtering works.  But that seems like a larger project than would fit in an issue about eliminating a rare error that occurs when a customized filtering fails.  

I suspect that this has always been broken on that site but had been just showing incorrect content.  The newer $brand version throws an error where the older version just happily did the wrong thing.  We can suppress the error in that case.  But it might be better to fix the custom filtering on that site.

**Comment by mfleeson** [comment]
In version 1.0.4.3 that I'm testing; cm_ip_title still references $brand as a global but searching through all of the source code for Phoenix it's not defined anywhere, which would explain it throwing an error when attempting to access the subfunction getData.

**Comment by ecartz** [comment]
@mfleeson $brand is defined in [includes/application_top.php](https://github.com/gburton/CE-Phoenix/blob/684951f08a5ed4d020b8a137a3850069c057ee41/includes/application_top.php#L362).

**Comment by mfleeson** [comment]
I'm so sorry, I ran a search in dreamweaver and hadn't seen it had changed from find in filesystem to find in open documents. I'll try and remove my comments.
