### ISSUE TITLE
Defunct config setting "PRODUCT_LIST_IMAGE"

### ISSUE THREAD

**Issue by raiwa** [gburton/CE-Phoenix#887]
Product image is flagged as defunct in Admin : Configuration : Product Listing, 
but still in use in:
- products_new.php
- specials.php.
- advanced_search_result.php
- includes\modules\content\index_products\cm_ip_product_listing.php

It should be removed in these files.

**Comment by gburton** [comment]
It's marked as a defunct setting, as it is defunct in terms of being set by the shopowners, but it is still used by the codebase.  It's of no importance at this point.  TY
