### ISSUE TITLE
Suggestion to make the address name on checkout_shipping_address clickable

### ISSUE THREAD

**Issue by chrbronikowski** [gburton/CE-Phoenix#893]
See [checkout_shipping_address.php](https://github.com/gburton/CE-Phoenix/blob/4459b90523c6d331084912a833496a61f62c997c/checkout_shipping_address.php#L236) file for reference.

On the checkout_shipping page, you are able to select either the shipping option (name) itself on the row or the actual radio button.  However, when you are on the checkout_shipping_address.php page, and looking to "choose a saved address" you must actually click on the actual radio button to change the selection. Based on some sample heat map click tracking customers are trying to actually select the option by first selecting the full address name, which does nothing. What are your thoughts on changing the code below:

Original
```
           <tr class="table-selection">
              <td><?php echo tep_address_format($format_id, $addresses, true, ' ', ', '); ?></td>
              <td align="text-right">
                <div class="custom-control custom-radio custom-control-inline">
                  <?php echo tep_draw_radio_field('address', $addresses['address_book_id'], ($addresses['address_book_id'] == $sendto), 'id="csa_' . $addresses['address_book_id'] . '" aria-describedby="csa_' . $addresses['address_book_id'] . '" class="custom-control-input"'); ?>
                  <label class="custom-control-label" for="csa_<?php echo $addresses['address_book_id']; ?>">&nbsp;</label>
                </div>
              </td>
            </tr>
```

Suggestion
```
            <tr class="table-selection">
              <td>
                <div class="custom-control custom-control-inline">
                  <label class="" for="csa_<?php echo $addresses['address_book_id']; ?>">
			  <?php echo tep_address_format($format_id, $addresses, true, ' ', ', '); ?>
                  </label>
                </div>
              </td>
              <td align="text-right">
                <div class="custom-control custom-radio custom-control-inline">
                  <?php echo tep_draw_radio_field('address', $addresses['address_book_id'], ($addresses['address_book_id'] == $sendto), 'id="csa_' . $addresses['address_book_id'] . '" aria-describedby="csa_' . $addresses['address_book_id'] . '" class="custom-control-input"'); ?>
                  <label class="custom-control-label" for="csa_<?php echo $addresses['address_book_id']; ?>">&nbsp;</label>
                </div>
              </td>
            </tr>
```

**Comment by ecartz** [comment]
I hope you don't mind, but I edited your post to make the code more readable.  As best I understand, you want to replace the existing [line 237 of checkout_shipping_address.php](https://github.com/gburton/CE-Phoenix/blob/4459b90523c6d331084912a833496a61f62c997c/checkout_shipping_address.php#L237):  

```
              <td><?php echo tep_address_format($format_id, $addresses, true, ' ', ', '); ?></td>
```
with 
```
              <td>
                <div class="custom-control custom-control-inline">
                  <label class="" for="csa_<?php echo $addresses['address_book_id']; ?>">
			  <?php echo tep_address_format($format_id, $addresses, true, ' ', ', '); ?>
                  </label>
                </div>
              </td>
```

Is all of that necessary?  I haven't tried it, but I would have thought that 

```
              <td><label for="csa_<?php echo $addresses['address_book_id']; ?>"><?php echo tep_address_format($format_id, $addresses, true, ' ', ', '); ?></label></td>
```

would be sufficient.  

I would also be curious if getting rid of 

```
                  <label class="custom-control-label" for="csa_<?php echo $addresses['address_book_id']; ?>">&nbsp;</label>
```

could be done without messing up the layout in some way.

**Comment by gburton** [comment]
It sounds like you want the header_tag modules which makes clicks in the table-row ... to be active on the checkout_shipping_address page ?

**Comment by ecartz** [comment]
For radio buttons it is sufficient to just make the text (the addresses) labels for the input (the radio buttons).  

You can see this working on the gender radios at https://template.me.uk/phoenix/create_account.php

**Comment by gburton** [comment]
https://github.com/gburton/CE-Phoenix/pull/894
