### ISSUE TITLE
.htaccess file in image directory issue

### ISSUE THREAD

**Issue by drillsar** [gburton/CE-Phoenix#900]
This isn't compatible with Apache 2.4. I purposed fix in pull request #899

**Comment by ecartz** [comment]
Apache 2.4 specifically includes a new mod_access_compat module to make the old form work in 2.4.  

Your suggested change does not match the current behavior and requires the file to be edited.  If we're requiring a file edit, we might as well ship with the old version and tell anyone who needs the new version to make an edit.  

There is more description about this at https://httpd.apache.org/docs/2.4/upgrading.html

According to https://w3techs.com/technologies/details/ws-apache/2 more than one in five Apache sites still use 2.2 or older.

**Comment by ecartz** [comment]
Correct form:  https://github.com/ecartz/CE-Phoenix/commit/1b396baacd3ccf4520ab868aae3609f1c5df5b72

Currently untested.
