### ISSUE TITLE
Email class duplicating extra headers

### ISSUE THREAD

**Issue by BrockleyJohn** [gburton/CE-Phoenix#901]
This change: [https://github.com/gburton/CE-Phoenix/commit/eb9adf40e0b98ed84150316f70594e512bbc6db9](https://github.com/gburton/CE-Phoenix/commit/eb9adf40e0b98ed84150316f70594e512bbc6db9)

dating back to the rush to frozen, "Remove Dupe email headers" is paradoxically introducing them.

Passing in a reply-to header doubles it - see output below.

This would be remedied by dropping $headers from the array_merge parameters
`$headers = array_merge($this->headers, array('From: ' . $from), $headers, $xtra_headers);`
but would that break something else that was being fixed at the time?

> $this->headers already set up Array
(
    [0] => MIME-Version: 1.0
    [1] => X-Mailer: osCommerce
    [2] => Content-Type: multipart/alternative;
	boundary="=_030eb35ddd30b525cdcd94c33a858810"
)
$headers passed in Array
(
    [0] => Reply-To: test@example.com
)
$xtra_headers derived Array
(
    [0] => Reply-To: test@example.com
)
headers to mail function Array
(
    [0] => MIME-Version: 1.0
    [1] => X-Mailer: osCommerce
    [2] => Content-Type: multipart/alternative;
	boundary="=_030eb35ddd30b525cdcd94c33a858810"
    [3] => From: "Johnny Tester" <contactform@example.com>
    [4] => Reply-To: test@example.com
    [5] => Reply-To: test@example.com
)

**Comment by BrockleyJohn** [comment]
Actually, the better question is - what was the duplication that was being fixed so it can be tested too?

**Comment by gburton** [comment]
Code came from HPDL if memory serves.  Feel free to patch and push a PR.

**Comment by ecartz** [comment]
The duplicate header being removed seems to have been the To address when the transport is SMTP.

**Comment by ecartz** [comment]
Is there any reason not to delete the admin email class?  The autoloader will fall back to the catalog version in that case.  One less file to maintain going forward and specifically in this case.

**Comment by gburton** [comment]
Anything that means fewer things to maintain is a good move in my opinion.

**Comment by ecartz** [comment]
Is there anything left with this issue?  Or can we close it now?

**Comment by ecartz** [comment]
I don't see anything left with this issue, so closing.
