### ISSUE TITLE
missing "tep_db_input(" in admin/modules.php

### ISSUE THREAD

**Issue by raiwa** [gburton/CE-Phoenix#905]
Using in config value sql sensitiv characters like single quote in "it's" breaks the db update query in line 38.
Suggested fix:
admin/modules.php line 38:
`          tep_db_query("update configuration set configuration_value = '" . tep_db_input($value) . "' where configuration_key = '" . $key . "'");
`

**Comment by ecartz** [comment]
https://github.com/gburton/CE-Phoenix/blob/44556a201fc8fdde7d261210402c55519d362af0/admin/modules.php#L46

Wow I'm fast.
