### ISSUE TITLE
Deprecate EMAIL_FROM?

### ISSUE THREAD

**Issue by ecartz** [gburton/CE-Phoenix#906]
The install creates a value called EMAIL_FROM by composition from the store owner's name and email address.  But there is no place where that information can be used in that way.  Because the email class takes the name and email address separately.  So we've been passing the EMAIL_FROM as the email address.  But that doesn't always work.  

We could separate EMAIL_FROM into a name and email address.  But we already have that information in the store. Do we really need it to be set twice?  

The simplest solution would be to just replace EMAIL_FROM in the three places it's used and remove it from the install entirely.

**Comment by BrockleyJohn** [comment]
It is useful on some platforms to be able to set the From address to be different to the To address, reducing the spam score for order emails to the store owner.

I have a related issue that I have been going to raise all week if I'd not been firefighting. The contact page currently sets the from address to the email in the form. This triggers on some platforms as spoofing and fails if spf is in use. 
It really ought to set the Reply-to address instead of the from.

My standard change for this is to add pass an extra parameter to the tep_mail function from contact_us.php and pass that into the extra headers for the mail class (guess what I was doing last weekend!)

**Comment by gburton** [comment]
I can't see any reasons other than Johns above.  You know my views on removal of redundancy;  "do it".

**Comment by ecartz** [comment]
> My standard change for this is to add pass an extra parameter to the tep_mail function from contact_us.php and pass that into the extra headers for the mail class (guess what I was doing last weekend!)

Wouldn't it make more sense to change [lines 381-3](https://github.com/gburton/CE-Phoenix/blob/981d119d29f3d1ebd40fa3fc01fe1aefd0ea1606/includes/classes/email.php#L381-L383) from 

```
      $headers = array_merge($this->headers, ['From: ' . $from], $this->normalize_headers($headers));

      return mail($to, $subject, $this->output, implode($this->lf, $headers), "-f$from_addr");
```

to 

```
      $headers = array_merge($this->headers, ['From: ' . EMAIL_FROM, 'Reply-to: ' . $from], $this->normalize_headers($headers));

      return mail($to, $subject, $this->output, implode($this->lf, $headers), '-f' . EMAIL_FROM);
```

You don't need an extra parameter, as the whole point of that change is to always send from the same address.  You only need to know the correct address to which to reply, which is already being passed.  

We could change core to say 

```
      if (defined('EMAIL_FROM')) {
        $sender_headers = ['From: ' . EMAIL_FROM, 'Reply-to: ' . $from];
      } else {
        $sender_headers = ['From: ' . $from];
      }

      $headers = array_merge($this->headers, $sender_headers, $this->normalize_headers($headers));

      return mail($to, $subject, $this->output, implode($this->lf, $headers), '-f' . EMAIL_FROM);
```

Then we can still deprecate setting EMAIL_FROM in the install, but you can still add it to the stores where you need it.

**Comment by BrockleyJohn** [comment]
I'm all for simpler solutions that are extensible. I'll try to make the time to stick it into a problematic site and check we're not missing anything.

**Comment by ecartz** [comment]
The SQL to add EMAIL_FROM to the configuration:

```
INSERT INTO configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) VALUES ('E-Mail From', 'EMAIL_FROM', 'root@localhost', 'All e-mails will be sent from this address', 12, 6, NOW());
```

Note that this moves it into the email settings rather than the My Store settings.  It also changes it to the email address, as that's what sendmail needs.  

Anyway, the proposed changes are implemented at https://github.com/gburton/CE-Phoenix/compare/1.0.5.4...ecartz:email_from?expand=1

**Comment by ecartz** [comment]
This is deployed in 1.0.5.5, so it seems reasonable to close this now.
