### ISSUE TITLE
undefined notice error in admin/reviews.php

### ISSUE THREAD

**Issue by raiwa** [gburton/CE-Phoenix#908]
When selecting a different than first row, an undefined notice error at line 319 for `$rInfo` is thrown.
Adding an isset check fixes it:
[admin/reviews.php line 319](https://github.com/gburton/CE-Phoenix/blob/981d119d29f3d1ebd40fa3fc01fe1aefd0ea1606/admin/reviews.php#L319):
`                <td class="dataTableContent" align="right"><?php if ( (isset($rInfo) && is_object($rInfo)) && ($reviews['reviews_id'] == $rInfo->reviews_id) ) { echo tep_image('images/icon_arrow_right.gif'); } else { echo '<a href="' . tep_href_link('reviews.php', 'page=' . $_GET['page'] . '&rID=' . $reviews['reviews_id']) . '">' . tep_image('images/icon_info.gif', IMAGE_ICON_INFO) . '</a>'; } ?>&nbsp;</td>
`

**Comment by ecartz** [comment]
We could do without the `is_object` check entirely if we just did 

```
                <td class="dataTableContent" align="right"><?php if ( isset($rInfo->reviews_id) && ($reviews['reviews_id'] == $rInfo->reviews_id) ) { echo tep_image('images/icon_arrow_right.gif'); } else { echo '<a href="' . tep_href_link('reviews.php', 'page=' . $_GET['page'] . '&rID=' . $reviews['reviews_id']) . '">' . tep_image('images/icon_info.gif', IMAGE_ICON_INFO) . '</a>'; } ?>&nbsp;</td>
```

Really, the question isn't if it's an object.  It's if it's set at all.  If it is set, it should always be an object.  In fact, we don't really need to check the existence of reviews_id.  But I think it is clearer why we are doing the check if we do.

**Comment by raiwa** [comment]
O.K., I agree.

**Comment by ecartz** [comment]
Added to 1.0.5.2.

https://github.com/gburton/CE-Phoenix/commit/3c869e4cda4710395a9dd68d68c3d31502ce9d10
