### ISSUE TITLE
Paypal Payment issue

### ISSUE THREAD

**Issue by drillsar** [gburton/CE-Phoenix#910]
After going through paypal and paying; if you back to cart and try to checkout again it gives you this error:

This invoice has already been paid.

**Comment by gburton** [comment]
Sounds more like a config issue.  On a successful paypal payment user should be redirected to checkout_success.  Do you have Paypal correctly set up?  instructions can be found at the forum I'd have thought or at library.oscommerce.com

**Comment by drillsar** [comment]
I did a brand new install and retrieved live and sandbox credentials. I checked the standard paypal and express. The standard I get this issue with express it goes through order fine.

**Comment by ecartz** [comment]
Which version?  

Do you have the return URL configured correctly in PayPal?  How?  How do you go "back to cart and try to checkout again"?  I.e. what buttons are you pressing?  Where do they lead?

**Comment by drillsar** [comment]
I have the return url configured to checkout_process.php in paypal website. I am using version 1.0.5.0 Phoenix.

**Comment by drillsar** [comment]
Well I put in Sandbox credentials manually and now fixed. I am guessing getting sandbox automatically an issue.
