### ISSUE TITLE
hide image output if no image in tpl_cm_in_category_listing.php

### ISSUE THREAD

**Issue by raiwa** [gburton/CE-Phoenix#913]
Image output should be conditioned if category image exists:
tpl_cm_in_category_listing.php line 8:
`        if (tep_not_null($v['image'])) echo '<a href="' . tep_href_link('index.php', 'cPath=' . $v['id']) . '">' . tep_image('images/' . $v['image'], htmlspecialchars($v['title'])) . '</a>';
`

**Comment by gburton** [comment]
This is what the Default Image functionality is for, no ?

**Comment by raiwa** [comment]
There are store owners not using categories images at all.

**Comment by raiwa** [comment]
OK, I have no default image defined and the alt text shows => duplicates category name.
Maybe I should define a blank pixel as default image?

**Comment by raiwa** [comment]
Image required set to false does the trick. Didn't play enough with the new settings it seems :-)
