### ISSUE TITLE
highlite selected modules in Admin bootstapped modules listings.

### ISSUE THREAD

**Issue by raiwa** [gburton/CE-Phoenix#915]
In Admin : Modules, Bootstrapped page versions, do not highlite the selected module.
It makes editing and installing more uncomfortable as it was in the old version.

**Comment by raiwa** [comment]
I suggest for example in admin/modules_content.php line 212 and 274:
`                echo '<tr class="table-active">';
`

If you wish I can push this for all module pages.

**Comment by gburton** [comment]
That would be great, thanks Rainer.

**Comment by raiwa** [comment]
to 1.0.5.2 ?

**Comment by raiwa** [comment]
conflict solved

**Comment by gburton** [comment]
TY
