### ISSUE TITLE
INSERT INTO configuration for cache during install

### ISSUE THREAD

**Issue by ReneH4** [gburton/CE-Phoenix#918]
I may be mistaken, but is this line still needed in the install SQL, since cache was dropped?

INSERT INTO configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) VALUES ('Cache Directory', 'DIR_FS_CACHE', '/tmp/', 'The directory where the cached files are saved', '11', '2', now());

**Comment by ecartz** [comment]
Yes, version check uses it.
