### ISSUE TITLE
Module Install Pages - top entry looks broken (refer screenshots)

### ISSUE THREAD

**Issue by peterpil19** [gburton/CE-Phoenix#922]
In 1.0.5.2, the module install page appears slightly broken with the name of the top entry obscured and the formatting off.

Here are screenshots from the navbar and header tags install pages:

<img width="1396" alt="Screen Shot 2020-02-25 at 10 06 34 am" src="https://user-images.githubusercontent.com/55443201/75201764-3ea83a00-57b9-11ea-9978-625a2c8b8289.png">

<img width="1384" alt="Screen Shot 2020-02-25 at 10 04 37 am" src="https://user-images.githubusercontent.com/55443201/75201767-41a32a80-57b9-11ea-8b11-74ecb6e31231.png">

**Comment by ecartz** [comment]
Is this on PHP 7.4, particular in XAMPP on Windows?  

What happens if you select a different row?  

What actual modules are these?  

Why is your Sort Order not showing?  

Do you have log messages?

**Comment by ecartz** [comment]
TY.  This was a missing quotation mark.  https://github.com/gburton/CE-Phoenix/commit/faaa03b01caf32e722cb933e0e42e4e8ddbe39ee
