### ISSUE TITLE
Paypal configure menu text alignment

### ISSUE THREAD

**Issue by peterpil19** [gburton/CE-Phoenix#923]
Minor issue but the text alignment makes selecting the options a little more confusing (refer screenshot).

<img width="1371" alt="Screen Shot 2020-02-25 at 8 55 16 pm" src="https://user-images.githubusercontent.com/55443201/75239008-d5a0e080-5811-11ea-9e1e-a60a1b7e0e69.png">

**Comment by gburton** [comment]
![new_paypa](https://user-images.githubusercontent.com/61020/95483643-67b3be80-0987-11eb-919c-54775d7d4a4b.jpg)

Updated Menu for Paypal now looks like this.
Will drop into 1.0.7.10
