### ISSUE TITLE
Insufficient Stock display in cart

### ISSUE THREAD

**Issue by gburton** [gburton/CE-Phoenix#927]
The change to this function;
https://github.com/gburton/CE-Phoenix/blob/master/includes/functions/general.php#L133-L135
results in a problem display when showing a product with insufficient stock.

**Comment by ecartz** [comment]
https://github.com/gburton/CE-Phoenix/commit/31a3fd6c6f0c0bc4bcc6a63f63b183cf804bd820

**Comment by gburton** [comment]
I didn't want to go ahead and revert the function change as I guessed it had deeper meaning inthe context of the recent changeset.  Thanks @ecartz

**Comment by gburton** [comment]
It also may have helped if I had been using latest 1053 rather than live 1052.  Ack.
