### ISSUE TITLE
1.0.5.7 - Installation screen breaks on Chrome

### ISSUE THREAD

**Issue by cupidare** [gburton/CE-Phoenix#947]
![image](https://user-images.githubusercontent.com/22186911/78552744-56d39600-7808-11ea-880f-55fe72d15f78.png)

trying to make a fresh install... on smaller viewports it seems to be ok

**Comment by ecartz** [comment]
It does this on Firefox too.

**Comment by gburton** [comment]
In this case is it because the PHP version is very long, therefore pushing the table too wide?
