### ISSUE TITLE
It did not display the child category in the box categories

### ISSUE THREAD

**Issue by Josex2021** [gburton/CE-Phoenix#951]
I'm reviewing the code and i can't figure it out what is missing... but something is.. because it can't display the child category only the parent ones, i suppose the error maybe in the class but if you can help me... and others because i don't think i'm the only one with this bug. thanks in advance...

**Comment by MOPS-DanCole** [comment]
Do you have products at the same level as the child-categories ie not in a child-category?  That has been a known issue for years.

**Comment by gburton** [comment]
The categories box shows only 1 level.  If you need more, make a new box module.

**Comment by Josex2021** [comment]
> Do you have products at the same level as the child-categories ie not in a child-category? That has been a known issue for years.

Thank you very much, i review the past issues and i delete the products even if they were turn off did not show the sub categories, when i delete those, bum... they appear, Regards...
