### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by tvplinux** [gburton/CE-Phoenix#954]
Dear gburton, many thanks to keep going with this project of the next generation of Oscommerce. In fact im developing a ERP that conect with oscommerce, and I would like to know if you have in your mind modify the database structure in a future. Im asking this could cause a future incompatibity issues with external software.

Thank you!!!

**Comment by gburton** [comment]
Possibily - it's hard to know what the future brings until it arrives.
Sorry that is not of much help at this point.
