### ISSUE TITLE
problem submitting form

### ISSUE THREAD

**Issue by hungryfrank** [gburton/CE-Phoenix#956]
let me just say that this might be somehow my fault
I can not submit the forms in the admin section, for example editing the modules.  on versions over 10.0.5.2
with Firefox I can submit some.  
with safari I can not login the admin to investigate further
what I get was a message that server dropped the connection and did not return anything.
problem goes away when I switch back to php7.1.33
from 7.3 
now I am on Mac Mojave internal server. and I had a problem installing php 7.3

**Comment by gburton** [comment]
An example URL of a form that works?
An example URL of a form that does not?

Have you tried on a real server?

**Comment by hungryfrank** [comment]
I will upgrade to 7.3 later
but I could not update any of the modules in safari
could do it in Firefox
older chroma 2yrs couldn't log me in

**Comment by hungryfrank** [comment]
http://localhost/m8/admin/login.php?action=process
on old chroma. 
This page isn’t workinglocalhost didn’t send any data.
ERR_EMPTY_RESPONSE
fire fox logs me in

  | Value
-- | --
Server Host | localhost (127.0.0.1)
Database Host | localhost (127.0.0.1)
Server OS | Darwin 18.7.0
Database | MySQL 8.0.18
Server Date | 2020-04-20 15:25:49 +0000 UTC
Database Date | 2020-04-20 19:55:49
Server Up Time | 19:55 up 4 mins, 2 users, load averages: 2.78 4.11 2.22
HTTP Server | Apache/2.4.34 (Unix) PHP/7.3.16
PHP Version | 7.3.16 (Zend 3.3.16)

**Comment by hungryfrank** [comment]
safari 13.1. has one update
logs me in 
http://localhost/m8/admin/modules.php?set=header_tags&module=ht_breadcrumb_schema&action=save

dosen't save  gives me server drop error

if I refresh the values are saved.

**Comment by hungryfrank** [comment]
this is crazy 
I just noticed that if I go to 
localhost/catalog it works
I I go to localhost/catalog/index.php
it dose not
and 
localhost/catalog/index.php?manufacturers_id=2
works

**Comment by hungryfrank** [comment]
sorry to leave so many comment. 
just try to be helpful.
the problem starts from  v1.0.5.2.  
I checked back.  v1.0.5.0 works fine

**Comment by hungryfrank** [comment]
I don't know what I was doing but Firefox gave a warning that it prevented a dangerous header or something like that. It hat to do with to_shipping and to_subtotal 
about this line. 
`    $module = substr($_SESSION['shipping']['id'], 0, strpos($_SESSION['shipping']['id'], '_'));

also I had a problem with the same line when I was trying to install order editor
and it was getting warnings about not being able to find the order total modules and its languages from a call from version 1.0.01 

I don't know if it is helpful or not
if you want I will go to php7.3 and try to find the errors and post it 
`

**Comment by BrockleyJohn** [comment]
It looks to me like you have could some problems with the dev server build - but not consistent ones across php versions. Sessions and requests may not be working properly.

Secondly, you may have added some dodgy customisation. The string "strpos($SESSION['shipping']['id']" does not appear in core code at 1.0.5.2

Try a clean install of 1.0.5.2 on your dev server setup and see if it works.

**Comment by hungryfrank** [comment]
the first part is possible.  but fresh install gave me same problem

**Comment by gburton** [comment]
I'm going to close this for now until you can install on a real server and test there.  Testing on Macs inbuilt server where we do not know what your settings are...is a wild goose chase for us.

If you want to write down your further testing, you can use the osCommerce forum if you wish to - it might be that someone else there has similar issues.

TY

**Comment by hungryfrank** [comment]
no if you feel that there is no problem it is good enough for me. no extra testing needed by me.
thanks
