### ISSUE TITLE
admin/backup.php fix

### ISSUE THREAD

**Issue by BecRoM** [gburton/CE-Phoenix#958]
- The first DROP TABLE in the .sql backup is commented.
- In CREATE TABLE allways add a space, even when haven't extra data.
- Extra data are lowercase instead of uppercase.

I have the file ready for create a PR to 1.0.5.9

**Comment by ecartz** [comment]
It is easier to understand your proposal at https://github.com/BecRoM/CE-Phoenix/commit/79857050a61590e957e4df2bcecfcab9e0392270

But anyway:  https://github.com/gburton/CE-Phoenix/commit/ecc8420af8bd0c2a814ce5a5fb14ab42d85c2cea
