### ISSUE TITLE
Warning: Use of undefined constant MODULE_BOXES_CATEGORIES_MAX_LEVEL

### ISSUE THREAD

**Issue by gadlol** [gburton/CE-Phoenix#959]
Warning: Use of undefined constant MODULE_BOXES_CATEGORIES_MAX_LEVEL - assumed 'MODULE_BOXES_CATEGORIES_MAX_LEVEL' (this will throw an Error in a future version of PHP) in /var/www/html/***/includes/modules/boxes/bm_categories.php on line 36

**Comment by ecartz** [comment]
Have you tried uninstalling and reinstalling the categories box?

**Comment by gadlol** [comment]
When uninstalling and reinstalling it works because the key is added to db. The MODULE_BOXES_CATEGORIES_MAX_LEVEL key is not installed in the db when installed a fresh installation with the option to add demo data.

**Comment by gburton** [comment]
Please always check latest thread in Phoenix Club and/or latest commits to see if raised bug has already had attention.  TY

**Comment by gadlol** [comment]
How am I supposed to check latest thread in Phoenix Club since I get:

Removed From Club
You were removed from this club by a leader. You won't be able to rejoin unless invited by leader.

Ok.. I am sorry, I just wanted to help but from what I see you don't need it...

**Comment by MOPS-DanCole** [comment]
Don't take it personal, there was just some culling of those who weren't active within the club.  Apply again, I'm sure Gary will give you access.

**Comment by gburton** [comment]
Inactive Member Pruning happens on a monthly basis. You may get caught up in that if you don't post - it's nothing personal - just PM me and you can be re-added if you are going to be an active member of the club.

Bystanders and tyre-kickers are not useful people.

Even if you were not a member, you could still have taken 2 minutes to look at the latest commits to see if it has been noted and solved.
