### ISSUE TITLE
Restock product quantity on deleting order not working

### ISSUE THREAD

**Issue by TonyDias** [gburton/CE-Phoenix#964]
Hi, 
version 1.0.5
On admin when deleting orders not paid, the product quantity is not restocked, even if the "Restock Quantity" option is enabled

**Comment by gburton** [comment]
Update to v1060 and report if same occurs.
Always give full version number.  Always give list of addons added and any other code changes made.

You might find it easier to ask general questions like this in the Phoenix Club at the osCommerce Forum.
