### ISSUE TITLE
admin/orders move updateAction hook before message stack

### ISSUE THREAD

**Issue by raiwa** [gburton/CE-Phoenix#966]
In [admin/orders.php line 71](https://github.com/gburton/CE-Phoenix/blob/master/admin/orders.php#L71):
```
        $OSCOM_Hooks->call('orders', 'updateAction');
```
should be moved before the message stack snippet ([lines 65-9](https://github.com/gburton/CE-Phoenix/blob/master/admin/orders.php#L65..69)):
```
        if ($order_updated == true) {
          $messageStack->add_session(SUCCESS_ORDER_UPDATED, 'success');
        } else {
          $messageStack->add_session(WARNING_ORDER_NOT_UPDATED, 'warning');
        }
```
to allow the hook code to set $order_updated = true to trigger the message stack if it updates something.

**Comment by gburton** [comment]
https://github.com/gburton/CE-Phoenix/pull/965/commits/2e0776319b552007f8eb446edc26a7e73a68752f
