### ISSUE TITLE
duplicate case 'NULL': and case 'NOW': in includes\functions\database.php

### ISSUE THREAD

**Issue by cupidare** [gburton/CE-Phoenix#967]
was this intended?

`foreach($data` as $value) {
        switch ((string)$value) {
          **case 'NOW()':
          case 'now()':**
            $query .= 'NOW(), ';
            break;
          **case 'NULL':
          case 'null':**
            $query .= 'NULL, ';
            break;
          default:
            $query .= '\'' . tep_db_input($value) . '\', ';
            break;
        }
      }
      $query = substr($query, 0, -2) . ')';
    } elseif ($action == 'update') {
      $query = 'UPDATE ' . $table . ' SET ';
      foreach($data as $columns => $value) {
        switch ((string)$value) {
          **case 'NOW()':
          case 'now()':**
            $query .= $columns . ' = NOW(), ';
            break;
          **case 'NULL':
          case 'null':`**

**Comment by ecartz** [comment]
Is the question if it is intended that either capitalization matches?  Or that insert and update have similar but different cases?  Yes to either of those.
