### ISSUE TITLE
admin/orders.php comment titel and space in status mail

### ISSUE THREAD

**Issue by raiwa** [gburton/CE-Phoenix#968]
Order status update mail includes comment title and space even when comments are empty.
[admin/orders.php line 49](https://github.com/gburton/CE-Phoenix/blob/master/admin/orders.php#L49) should be changed to:
`
            if (isset($_POST['notify_comments']) && ($_POST['notify_comments'] == 'on') && tep_not_null($comments) ) {
`
or
`
            if (isset($_POST['notify_comments']) && ($_POST['notify_comments'] == 'on') && $comments != '' ) {
`

**Comment by gburton** [comment]
Why?

If the shopowner ticks "add comments", the comment gets added.  
If there is no comment, the shopowner should untick the box.

**Comment by raiwa** [comment]
It's ticked by default. If the shopowner forgets to untick and leaves the comments empty, the mail includes the title and ampty space, but no comment.

**Comment by gburton** [comment]
Then the shopowner needs to be awake when updating orders.
