### ISSUE TITLE
SEO Breadcrumb

### ISSUE THREAD

**Issue by BecRoM** [gburton/CE-Phoenix#970]
SEO Breadcrumb can be overrided, but by the products/category/manufacturer title instead of a custom Breadcrumb.

I write on forum to get help to make it as addon or similar using Hooks, but not have help.

I write this, but it's core changed, I put here for if someone think that will be added:

https://github.com/BecRoM/CE-Phoenix/commit/36ec2009271b325376eceea8802bbcbfaff5ef2c

PS: sorry for my google translated english

**Comment by gburton** [comment]
What do these changes enable that is not already available in Core Code?

**Comment by BecRoM** [comment]
The actual Core Code offer the posibility to overried Breadcrumb Trail by SEO Title, with these changes you can set a custom SEO Breadcrumb Trail for the product / category / manufacturer.

Similar as you can set a custom Title, can set a custom Breadcrumb

This offer to shopowner a full options to make SEO as other SEO addons in osCommerce or WoCommerce and similars.

**Comment by gburton** [comment]
It really makes no sense to make this change (unless I am missing something)...as you can already override the breadcrumb in Core Code.
See, eg: https://template.me.uk/phoenix/product_info.php?products_id=6
Where I changed the breadcrumb to "GreenTom".

**Comment by BecRoM** [comment]
And it's possible to set a custom SEO Title and a different SEO Breadcrumb at time?

Theses changes are to set different SEO Title, SEO Breadcrumb because I didn't find the way to make it.

I think you disabled override SEO Title but have enabled Breadcrumb override, did you do this?

**Comment by gburton** [comment]
> I think you disabled override SEO Title but have enabled Breadcrumb override

Correct.


> it's possible to set a custom SEO Title and a different SEO Breadcrumb

For what reason ?

**Comment by BecRoM** [comment]
SEO reasons, when you make a search on Google (on desktop), Breadcrumb are show in results, you can choose what you want to show there, this way you can work with more keywords to show product / category / manufacturer.

Breadcrumb it's a internal link, and the possibility to configure this anchor text it's good for SEO.

Or for example, you can have a Title product too long (the store name it's append at end) and you want to have a breadcrumb with a little bit more text in this link

**Comment by gburton** [comment]
OK.  I thank you for the interest, but I don't think we will go down this path at this time.

TY.
