### ISSUE TITLE
admin categories.php input fields css classes are in wrong parameter position

### ISSUE THREAD

**Issue by raiwa** [gburton/CE-Phoenix#975]
within the tep_input_field function the css classes are included in the parameter position and should be in the class position. This produces duplicated class tag.
Example:
`            echo tep_draw_input_field('products_price', $pInfo->products_price, 'id="pNet" class="form-control w-25" onchange="updateGross()"');
`
output:
`<input type="text" name="products_price" value="4.9900" id="pNet" class="form-control w-25" onchange="updateGross()" class="form-control" />`

it should be:
`            echo tep_draw_input_field('products_price', $pInfo->products_price, 'id="pNet" onchange="updateGross()"', 'text', true, 'class="form-control w-25"');
`
output:
`<input type="text" name="products_price" value="4.9900" id="pNet" onchange="updateGross()" class="form-control w-25" />`

**Comment by ecartz** [comment]
It might be easier to change tep_draw_input_field.  

```
if (tep_not_null($class) && (false === strpos($parameters, 'class="'))) $field .= " $class";
```

Not tested.

**Comment by raiwa** [comment]
Confirmed, works nice.

**Comment by gburton** [comment]
TY both
