### ISSUE TITLE
missing column list in admin products attributes add_products_attributes query

### ISSUE THREAD

**Issue by raiwa** [gburton/CE-Phoenix#976]
I have additional columns added to the products_attributes table.
when inserting a new product attribute, the query throws the following error:
`1136 - Column count doesn't match value count at row 1
insert into products_attributes values (null, '3', '1', '2', '3', '+')`
adding the column list fixes it in admin/products_attributes.php line 66:
`        tep_db_query("insert into products_attributes (products_attributes_id, products_id, options_id, options_values_id, options_values_price, price_prefix) values (null, '" . (int)$products_id . "', '" . (int)$options_id . "', '" . (int)$values_id . "', '" . (float)tep_db_input($value_price) . "', '" . tep_db_input($price_prefix) . "')");
`

**Comment by ecartz** [comment]
With the column list 
```
tep_db_query("insert into products_attributes (products_id, options_id, options_values_id, options_values_price, price_prefix) values ('" . (int)$products_id . "', '" . (int)$options_id . "', '" . (int)$values_id . "', '" . (float)tep_db_input($value_price) . "', '" . tep_db_input($price_prefix) . "')");
```
would be better.

**Comment by gburton** [comment]
There may be other such SQL inserts that will need to be amended similarly.

**Comment by raiwa** [comment]
Yes, this is reqired to allow addons to add columns without the need to modify core queries.

**Comment by gburton** [comment]
Yes, I understand.  We will do this at some point in the 1.0.7.x release line.
If you find any more, please list them here if you have time to do so.

**Comment by raiwa** [comment]
O.K. will do

**Comment by gburton** [comment]
If you have a copy with the SQL changes only, that would be ideal.  Thank You.
Code is static at the moment to allow Matt to get his Template system up and running, but I will let you know when/where to push it..

**Comment by raiwa** [comment]
DONE
I also included the move of insert id, hope it's ok

**Comment by gburton** [comment]
Please update your files to v1.0.7.3 (there has been a lot of changes, including one in the products_attributes.php file).  If you then make your needed changes and push back to v1.0.7.3 that would be great.  TY

**Comment by ecartz** [comment]
As best I understand, your [PR](https://github.com/gburton/CE-Phoenix/pull/982) fixed this, so closing.  If there's something else, please reopen and specify what else is needed.

**Comment by raiwa** [comment]
There is the problem with missplaced form tags:

I inject additional price values into the Products Attributes table and below into the add attributes line via siteWide hook.
The values are not submitted because of the missplaced form.
They also do not html validate as they are placed inside the table rows.
For this table the form can be moved outside the table tags so my injected input field values get submitted. ( not sure if I miss something here, but it works for me).
The other tables have multiple forms which also do not get html validated, but no idea how to easy fix it.

**Comment by gburton** [comment]
You'd need to;

1.  point out the misplaced form tags and say where they should be (I see no misplaced tags)
2.  explain what you are doing with siteWide hooks (I assume injecting with javascript)
3.  what you are trying to do with HTML validation (has nothing to do with table rows)

But not here.  Please do that at the Phoenix Club, along with screenshots etc to illustrate.
