### ISSUE TITLE
admin/define languages strips backslash

### ISSUE THREAD

**Issue by raiwa** [gburton/CE-Phoenix#989]
In admin/define_languages.php line 76:
`            $file_contents = stripslashes($_POST['file_contents']);
`

strips backslashes. It's just what it shouldn't do, they are required to escape single quotes.

Suggested change:
`            $file_contents = $_POST['file_contents'];
`

**Comment by gburton** [comment]
Please try:

$file_contents = tep_sanitize_string($_POST['file_contents']);

**Comment by raiwa** [comment]
Not good. This converts all html opening and closing tags to underscore:
<li> becomes _li_

**Comment by raiwa** [comment]
If no one noticed this since 2.2MS1, that means that no one uses it.
Maybe just remove this page like the file edit page was removed.
