### ISSUE TITLE
E-Mail-Header encoding issue

### ISSUE THREAD

**Issue by cupidare** [gburton/CE-Phoenix#992]
As mentioned here 

https://forums.oscommerce.com/topic/495665-e-mail-header-encoding-issue/?tab=comments#comment-1811218

some email-providers bounce mails which have a not utf-8 encoded header. The most affected variables are
- to-name
- from-name
- subject

I would suggest to test whether an encoding is necessary (if this is easy and possible) and then encode this. As mentioned in the forum-post encoding it with base64 works for me and another guy without any further issues...

**Comment by ecartz** [comment]
I think that the larger question is if it works with providers/fields not using UTF-8 but simply ASCII.  I.e. are there any circumstances when this breaks currently working emails?

**Comment by cupidare** [comment]
the encoding of the header is still 7Bit therefore ascii... all providers I am aware of use some kind of encoding for ascii characters in the header.

**Comment by cupidare** [comment]
I again had a look on this subject. It should be enough to encode the strings only if it is necessary:

>   
      if (mb_detect_encoding($to_name, ["ASCII","UTF-8"]) == "UTF-8"){
        $to_name = '=?utf-8?B?' . base64_encode($to_name) . '?=';
      }
      if (mb_detect_encoding($from_name, ["ASCII","UTF-8"]) == "UTF-8"){
        $from_name = '=?utf-8?B?' . base64_encode($from_name) . '?=';
      }
      if (mb_detect_encoding($subject, ["ASCII","UTF-8"]) == "UTF-8"){
        $subject = '=?utf-8?B?' . base64_encode($subject) . '?=';
      }

**Comment by ecartz** [comment]
Probably need to wrap in `if (function_exists('mb_detect_encoding')) {`as I don't believe that we otherwise require the multibyte extension to be installed.

**Comment by cupidare** [comment]
maybe a lightweight wrapper for mb_detect_encoding using a simple schematic that just checks for a non-ASCII char?

### function ASCII_check($string) { 
    $sample = iconv('ASCII', 'ASCII//IGNORE', $string);
     {
        return (md5($sample) != md5($string)) ? 'non-ASCII' : 'ASCII' ;
    }
}
$string = 'ä';
echo ASCII_check($string);

**Comment by ecartz** [comment]
More checking suggests that iconv is also not guaranteed to be present, so we should replace mb_detect_encoding with 

```
if (preg_match('{[\x80-\xFF]}', $subject)) {
```

**Comment by cupidare** [comment]
It seems to work identical ... so for me it would be ok
